<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Chapter 5 - Data Cleaning • motus</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../../bootstrap-toc.css">
<script src="../../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><meta property="og:title" content="Chapter 5 - Data Cleaning">
<meta property="og:description" content="motus">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">motus</a>
        <span class="version label label-info" data-toggle="tooltip" data-placement="bottom" title="Documentation overhaul">4.0.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../articles/articles/motus.html">Get started</a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/articles/01-introduction.html">Chapter 1 - Introduction</a>
    </li>
    <li>
      <a href="../../articles/articles/02-installing-packages.html">Chapter 2 - Installing packages</a>
    </li>
    <li>
      <a href="../../articles/articles/03-accessing-data.html">Chapter 3 - Accessing detections data</a>
    </li>
    <li>
      <a href="../../articles/articles/04-deployments.html">Chapter 4 - Tag and receiver deployments</a>
    </li>
    <li>
      <a href="../../articles/articles/05-data-cleaning.html">Chapter 5 - Data Cleaning</a>
    </li>
    <li>
      <a href="../../articles/articles/06-exploring-data.html">Chapter 6 - Exploring detections data</a>
    </li>
    <li class="divider">
    <li>
      <a href="../../articles/index.html">More...</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="05-data-cleaning_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Chapter 5 - Data Cleaning</h1>
            
      
      
      <div class="hidden name"><code>05-data-cleaning.Rmd</code></div>

    </div>

    
    
<blockquote>
<p>In this chapter we’ll go through checking and cleaning tag detections by by filtering out noisy data, visually exploring your data, and checking ambiguous detections.</p>
<p>Some extra, more advanced topics not addressed in this chapter are available as supplementary articles.</p>
<p><strong>Advanced Topics:</strong></p>
<ul>
<li><a href="filtering.html">In-depth detections filtering</a></li>
<li><a href="gps.html">Working with GPS points</a></li>
</ul>
</blockquote>
<p>There are three sources of ‘error’ that can result in tag detections appearing in your database that are incorrect.</p>
<p>First, random radio noise (‘static’) can be detected and interpreted to be the transmission of a tag. These are called ‘false positives’.</p>
<p>Second, despite our best efforts to avoid it, duplicate tags are sometimes transmitting in the network at the same time. When two tags are deployed at the same time that have the same ID code, burst interval, and nominal transmit frequency, it results in situations where the detections may belong to either tag. If that happens, we must rely on contextual information to separate them (if we can). We term these ‘Ambiguous tags’.</p>
<p>Third, a tag can appear to be present when two tags are transmitting at the same time that by chance produce a signal that looks like a third tag that is not in fact present. Such tags are most common at roosting sites or breeding colonies, where many tags are transmitting simultaneously. We term these ‘Aliased tags’. We do not deal explicitly with Aliased tags in this chapter; we are working on a way to globally identify them and eliminate them from the data. We mention them here because you may encounter situations with what appear to be highly plausible detections that don’t make biological sense. Please contact us if you think you have some of these Aliased tag detections in your database.</p>
<p>The <em>goal of this chapter</em> is to provide you with the tools you need to check your data for false detections, and remove them from your data. We do so by providing example workflows that deal with ‘false positives’ and ‘ambiguous tags’ in the following steps:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Preliminary Filter</strong><br>
A run is a group of consecutive detections of a tag detected on a single antenna at a single receiver. Very short runs and relatively short runs at noisy stations both have a high probability of being false positive detections. These can be omitted using the <code>motusFilter</code>. However, because you will likely lose some true detections in the process, we also recommend that after a full analysis of your data, you return to these detections and examine them individually, to determine (usually contextually) if they can be considered real.</p></li>
<li><p><strong>Examine individual tags</strong><br>
Examine indiviudal tags and determine if runs in those tags are errors</p></li>
<li><p><strong>Ambiguous Detections</strong><br>
Determine how many of your tag detections may be ambiguous detections</p></li>
<li><p><strong>Remove false detections from your data</strong></p></li>
</ol>
<div id="load-required-packages" class="section level2">
<h2 class="hasAnchor">
<a href="#load-required-packages" class="anchor"></a>Load required packages</h2>
<p>Follow the instructions in <a href="02-installing-packages.html">Chapter 2</a> to install the following packages before loading, if they are not already installed.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">motus</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lubridate.tidyverse.org">lubridate</a></span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/Sys.setenv.html">Sys.setenv</a></span><span class="op">(</span>tz <span class="op">=</span> <span class="st">"UTC"</span><span class="op">)</span></code></pre></div>
</div>
<div id="load-detections-data" class="section level2">
<h2 class="hasAnchor">
<a href="#load-detections-data" class="anchor"></a>Load detections data</h2>
<p>Recall from <a href="03-accessing-data.html#user-authentication">Chapter 3</a> that when accessing the sample database, you will need to input <code>motus.sample</code> in the R console as both username and password when prompted by the <code><a href="../../reference/tagme.html">tagme()</a></code> user authentication process. This section assumes you have already completed the <a href="03-accessing-data.html#downloading-tag-detections">initial sample data download</a>.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sql.motus</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/tagme.html">tagme</a></span><span class="op">(</span><span class="fl">176</span>, update <span class="op">=</span> <span class="cn">TRUE</span>, dir <span class="op">=</span> <span class="st">"./data/"</span><span class="op">)</span></code></pre></div>
<pre><code>## Checking for new data in project 176</code></pre>
<pre><code>## activity:     0 new batch records to check</code></pre>
<pre><code>## nodeData:     0 new batch records to check</code></pre>
</div>
<div id="assess-tag-detections" class="section level2">
<h2 class="hasAnchor">
<a href="#assess-tag-detections" class="anchor"></a>Assess tag detections</h2>
<p>First, determine which project tags have detections. There are several reasons why deployed tags might not be detected, including:</p>
<ol style="list-style-type: decimal">
<li><p>The tag was not properly activated on deployment. To avoid this, always check that a tag is active using a hand-held receiver before attaching the tag to your study animal and releasing it.</p></li>
<li><p>An animal with a properly activated tag might not have passed within range of a receiving station. Study designs that incorporate strategic placement of receivers to meet project goals can improve the probability of a tag being detected.</p></li>
<li><p>Missing or incorrect tag deployment metadata in the Motus database can result in the data processing algorithm not ‘looking’ for your tag at the time the tag was deployed, or at all. Please ensure your tag metadata are entered correctly.</p></li>
</ol>
<p>Before going further, <strong>please check whether any of your tags were deployed more than once</strong>, as described in <a href="#number-of-deployments-per-tag">Chapter 4 - Number of deployments per tag</a>. If so, you will need to use <code>tagDeployID</code> or a combination of <code>motusTagID</code> and <code>tagDeployID</code> to uniquely define detections associated with a tag deployment (either will do, but combining the two fields will let you know which tagID is associated with each deployment).</p>
<p>In the sample data, all tags were deployed only once, and so we use the <code>motusTagID</code> as a unique identifier for a tag deployment in all R code throughout these articles</p>
</div>
<div id="preliminary-filtering" class="section level2">
<h2 class="hasAnchor">
<a href="#preliminary-filtering" class="anchor"></a>Preliminary filtering</h2>
<p>Invariably you will run into some false detections in your tag detection data. Sometimes these may be due to random glitches or noisy radio conditions. The various outputs on the Motus web site are pre-filtered, but data downloaded via the <code>motus</code> R package provides access to <strong>all</strong> detections, allowing users more control over which detections to keep or omit. Therefore, it is important to filter these out as part of your data cleaning process.</p>
<p>As runs are composed of sequences of hits, the longer the run the more confident we can be that it represents a true detection. However, local conditions at an individual receiver may vary in their exposure to background radio noise/interference. Sites with relatively more background noise may be more prone to generating a high number of very short runs that are in reality spurious data.</p>
<p>There are two filtering options in the <code>motus</code> R package that follow these ideas:</p>
<ol style="list-style-type: decimal">
<li>Easiest is the field/column called <code>motusFilter</code> found in the <code>runs</code> table and <code>alltags</code> view</li>
<li>More customizable, is the function called <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code>
</li>
</ol>
<blockquote>
<p>Here we will continue with the <code>motusFilter</code> column, and encourage users to check out the article on <a href="filtering.html">In-depth detections filtering</a> for more details on how the <code>motusFilter</code> is calculated and how to customize filtering with the <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function</p>
</blockquote>
<p><code>motusFilter</code> is a column in the <code>runs</code> table and is a good first option for identifying detections that have a higher probability of being false. Currently the <code>motusFilter</code> contains just two values <code>0</code> or <code>1</code>. Runs with a <code>motusFilter</code> of <code>0</code> are considered “invalid” (i.e. have a low probability of being true detections) and could therefore be omitted.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">hitID</span>, <span class="va">runID</span>, <span class="va">batchID</span>, <span class="va">ts</span>, <span class="va">motusFilter</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 5]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
##     hitID runID batchID          ts motusFilter
##     &lt;int&gt; &lt;int&gt;   &lt;int&gt;       &lt;dbl&gt;       &lt;int&gt;
##  1  45107  8886      53 1445858390.           1
##  2  45108  8886      53 1445858429.           1
##  3  45109  8886      53 1445858477.           1
##  4  45110  8886      53 1445858516.           1
##  5  45111  8886      53 1445858564.           1
##  6 199885 23305      64 1445857924.           1
##  7 199886 23305      64 1445857983.           1
##  8 199887 23305      64 1445858041.           1
##  9 199888 23305      64 1445858089.           1
## 10 199889 23305      64 1445858147.           1
## # … with more rows</code></pre>
<p>To omit dubious runs (0) and keep only ‘good’ runs (1) identified by <code>motusFilter</code> we <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> them out.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusFilter</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<p>To double check we can filter for short runs in the original <code>alltags</code> view</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">hitID</span>, <span class="va">runID</span>, <span class="va">batchID</span>, <span class="va">motusTagID</span>, <span class="va">runLen</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">runLen</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 5]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
##     hitID  runID batchID motusTagID runLen
##     &lt;int&gt;  &lt;int&gt;   &lt;int&gt;      &lt;int&gt;  &lt;int&gt;
##  1 516095 104118     141      16047      3
##  2 516096 104118     141      16047      3
##  3 516097 104119     141      16047      3
##  4 516098 104119     141      16047      3
##  5 516099 104118     141      16047      3
##  6 516100 104119     141      16047      3
##  7 516101 104120     141      16047      2
##  8 516102 104120     141      16047      2
##  9 516132 104133      97      16047      2
## 10 516133 104133      97      16047      2
## # … with more rows</code></pre>
<p>And compare this to our newly created filtered table <code>tbl.alltags.sub</code></p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">hitID</span>, <span class="va">runID</span>, <span class="va">batchID</span>, <span class="va">motusTagID</span>, <span class="va">runLen</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">runLen</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 5]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # … with 5 variables: hitID &lt;int&gt;, runID &lt;int&gt;, batchID &lt;int&gt;,
## #   motusTagID &lt;lgl&gt;, runLen &lt;int&gt;</code></pre>
<p>Note that the filters may exclude some true detections in the process. Therefore, we recommend that after a full analysis of your data, you return to these detections and examine them individually, to determine (usually contextually) if they can be considered real.</p>
<p>With that in mind, let’s keep track of the detections we’ve just removed.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusFilter</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
</div>
<div id="preliminary-data-checks" class="section level2">
<h2 class="hasAnchor">
<a href="#preliminary-data-checks" class="anchor"></a>Preliminary data checks</h2>
<p>Prior to more specific filtering the data, we will perform a few checks, summaries and plots of the data.</p>
<div id="checking-receivers" class="section level3">
<h3 class="hasAnchor">
<a href="#checking-receivers" class="anchor"></a>Checking receivers</h3>
<p>In our example, we will need to remove about 150 detections, because there is no geographic data associated with the receiver metadata, and so no way to determine the location of those detections.</p>
<p>For example, we can see which receivers are missing data by filtering by <code>is.na(recvDeployLat)</code> and <code>is.na(recvDeployName)</code></p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvDeployLat</span><span class="op">)</span> <span class="op">|</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvDeployName</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, <span class="va">recvDeployID</span>, <span class="va">recv</span>, 
         <span class="va">recvProjID</span>, <span class="va">recvProjName</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 7]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
##   recvDeployLat recvDeployLon recvDeployName recvDeployID recv        recvProjID
##           &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;                 &lt;int&gt; &lt;chr&gt;            &lt;int&gt;
## 1            NA            NA NP mobile              3813 Lotek-280          176
## 2            NA            NA &lt;NA&gt;                     NA SG-1415BBB…         NA
## 3            NA            NA &lt;NA&gt;                     NA SG-2814BBB…         NA
## # … with 1 more variable: recvProjName &lt;chr&gt;</code></pre>
<p>Notice that some of these receivers are also missing names.</p>
<p>As more users explore and fix their metadata, these missing values should begin to disappear.</p>
<p>If you don’t have any problems with your data, you can continue on with this walk-through.</p>
<p>However if you have multiple missing <code>recvDeployName</code> you may want to <a href="03-accessing-data.html#converting-to-flat-data">flatten your data</a> and change the names before proceeding. Here we make a new name from the latitude and longitude.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># flatten your data</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>recvDeployName <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvDeployName</span><span class="op">)</span>, 
                                  <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="st">":"</span>, <span class="va">recvDeployLon</span><span class="op">)</span>,
                                  <span class="va">recvDeployName</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<blockquote>
<p>If you take this route, remember that in all future examples you’ll want to use your new, flatted data frame <code>df.alltags.sub</code>, not the un-flatted <code>tbl.alltags.sub</code></p>
</blockquote>
<p><strong>Note:</strong> if you have GPS points in your data, you may wish to check out the article on <a href="gps.html">Working with GPS points</a>, particularly <a href="gps.html#using-gps-locations">the section</a> which details how you might wish to combine create new lat/lons with a combination of <code>recvDeployLat</code>/<code>recvDeployLon</code> and <code>gpsLat</code>/<code>gpsLon'</code></p>
</div>
<div id="summarize-tag-detections" class="section level3">
<h3 class="hasAnchor">
<a href="#summarize-tag-detections" class="anchor"></a>Summarize tag detections</h3>
<p>An initial view of the data is best achieved by plotting. We will show you later how to plot detections on a map, but we prefer a simpler approach first; plotting detections through time by both latitude and longitude. First however, we should simplify the data. If we don’t, we risk trying to plot thousands or millions of points on a plot (which can take a long time).</p>
<p><strong>Simplify the data for plotting</strong></p>
<p>We can simplify the data by summarizing by the <code>runID</code>. If you want to summarize at a finer/coarser scale, you can also create other groups. The simplest alternative is a rounded timestamp variable; for example by using <code>mutate(ts.h = plyr::round_any(ts, 3600)</code>. Other options are to just use date (e.g <code>date = as_date(ts)</code>).</p>
<p>Here we create a summary data frame that we can filter to produce different plots</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.plot</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tagProjID</span> <span class="op">==</span> <span class="fl">176</span>, <span class="co"># keep only tags registered to the sample project</span>
         <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvDeployLat</span><span class="op">)</span> <span class="op">|</span> <span class="op">!</span><span class="op">(</span><span class="va">recvDeployLat</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># drops data without lon/lat</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span>, <span class="va">recvDeployName</span>, <span class="va">ambigID</span>, 
           <span class="va">tagDepLon</span>, <span class="va">tagDepLat</span>, <span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="co">#summarizing by runID to get max run length and mean time stamp:</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>max.runLen <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">runLen</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, 
            ts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ts</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, .groups <span class="op">=</span> <span class="st">"drop"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">ts</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu">plyr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/plyr/man/round_any.html">round_any</a></span><span class="op">(</span><span class="va">ts</span>, <span class="fl">3600</span><span class="op">)</span>,
         ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span>, tz <span class="op">=</span> <span class="st">"UTC"</span>, origin <span class="op">=</span> <span class="st">"1970-01-01"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We would initially plot a subset of tags by either latitude or longitude<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, to get an overview of where there might be issues. Here, to simplify the example, we plot only six tags. We avoid examining the ambiguous tags for now.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.plot</span>,
                     <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16011</span>, <span class="fl">16035</span>, <span class="fl">16036</span>, <span class="fl">16037</span>, <span class="fl">16038</span>, <span class="fl">16039</span><span class="op">)</span><span class="op">)</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">recvDeployLat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">motusTagID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_date.html">scale_x_datetime</a></span><span class="op">(</span>date_labels <span class="op">=</span> <span class="st">"%Y-%m-%d"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>Although there don’t seem to be any immediate problems, let’s take a look at the tags showing up around 44 degrees during September. Let’s examine these tags in more detail by examining the runs in the data frame that are associated with detections in September.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16035</span>, <span class="fl">16037</span>, <span class="fl">16039</span><span class="op">)</span>,
         <span class="va">recvDeployLat</span> <span class="op">&lt;</span> <span class="fl">44</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span> <span class="op">==</span> <span class="fl">9</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">recvDeployName</span>, month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, <span class="va">runLen</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, 
            n.tags <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">motusTagID</span><span class="op">)</span><span class="op">)</span>, 
            .groups <span class="op">=</span> <span class="st">"drop"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">runLen</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 14 × 5
##    recvDeployName        month runLen     n n.tags
##    &lt;chr&gt;                 &lt;dbl&gt;  &lt;int&gt; &lt;int&gt;  &lt;int&gt;
##  1 Assateague State Park     9      6     6      1
##  2 FINWR                     9      6     6      1
##  3 FINWR                     9     10    10      1
##  4 FINWR                     9     20    20      1
##  5 Prime Hook                9     23    23      1
##  6 BULL                      9     24    24      1
##  7 Prime Hook                9     27    27      1
##  8 Bombay Hook               9     32    32      1
##  9 Prime Hook                9     32    32      1
## 10 Bombay Hook               9     36    36      1
## 11 BULL                      9     38    38      1
## 12 Port Maitland             9     42    42      1
## 13 Bombay Hook               9     53    53      1
## 14 FINWR                     9     73    73      1</code></pre>
<p>Since we have already filtered dubious detections, these remaining ones don’t seem immediately unreliable (all with high <code>runLen</code>). If you are interested, you can re-run the code above, but on the full data frame (<code>tbl(sql.motus, "alltags")</code>) containing run lengths of 2 or 3. You will see that there are likely false positive detections at these sites, that were already eliminated by filtering.</p>
<p>Hypothetically, if we decided that those detections in September were false positives, we could create a data frame that contains the <code>motusTagID</code>s and <code>runID</code>s for them.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.1</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16035</span>, <span class="fl">16037</span>, <span class="fl">16039</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span> <span class="op">==</span> <span class="fl">9</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>Remove them from our plotting data frame</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.plot.sub</span> <span class="op">&lt;-</span> <span class="va">df.plot</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">df.block.1</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"motusTagID"</span>, <span class="st">"runID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>And then plot our data again, having omitted those detections</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.plot.sub</span>,
                     <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16011</span>, <span class="fl">16035</span>, <span class="fl">16036</span>, <span class="fl">16037</span>, <span class="fl">16038</span>, <span class="fl">16039</span><span class="op">)</span><span class="op">)</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">recvDeployLat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">motusTagID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_date.html">scale_x_datetime</a></span><span class="op">(</span>date_labels <span class="op">=</span> <span class="st">"%Y-%m-%d"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-15-1.png" width="700"></p>
<p>The reader is encouraged to explore the rest of the tags within this group, to determine if there are additional false positives.</p>
</div>
</div>
<div id="examining-ambiguous-detections" class="section level2">
<h2 class="hasAnchor">
<a href="#examining-ambiguous-detections" class="anchor"></a>Examining ambiguous detections</h2>
<p>Before we go further, we need to check to see if any tags have ambiguous detections. If there are, we will need to explore them, and create additional filters to remove detections from our database.</p>
<p><strong>Are any of your tags associated with ambiguous detections?</strong></p>
<p>The <code><a href="../../reference/clarify.html">clarify()</a></code> function in the <code>motus</code> R package provides a summary of ambiguities in the detections data. Each <code>ambigID</code> refers to a selection of detections that could belong to one or more (up to 6) <code>motusTagID</code>s, which are listed in the <code>id1</code> to <code>id6</code> columns:</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/clarify.html">clarify</a></span><span class="op">(</span><span class="va">sql.motus</span><span class="op">)</span></code></pre></div>
<pre><code>##   ambigID numHits   id1                              fullID1   id2
## 1     -56    5734 22867 SampleData#272.1:5.3@166.38(M.22867) 23316
## 2    -106     279 17021        Selva#172:6.1@166.38(M.17021) 17357
## 3    -114      86 22897 SampleData#303.1:5.3@166.38(M.22897) 24298
## 4    -134   22749 22905   SampleData#301:5.3@166.38(M.22905) 23319
## 5    -171    2074 22778   RBrownAMWO#308:5.3@166.38(M.22778) 22902
## 6    -337       4 10811        Niles#152:6.1@166.38(M.10811) 16011
##                                fullID2   id3                         fullID3
## 1   SampleData#272:5.3@166.38(M.23316)    NA                            &lt;NA&gt;
## 2   SampleData#172:6.1@166.38(M.17357)    NA                            &lt;NA&gt;
## 3      NEONICS#303:5.3@166.38(M.24298)    NA                            &lt;NA&gt;
## 4 SampleData#301.1:5.3@166.38(M.23319)    NA                            &lt;NA&gt;
## 5 SampleData#308.1:5.3@166.38(M.22902) 24303 NEONICS#308:5.3@166.38(M.24303)
## 6   SampleData#152:6.1@166.38(M.16011)    NA                            &lt;NA&gt;
##   id4 fullID4 id5 fullID5 id6 fullID6 motusTagID tsStart tsEnd
## 1  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 2  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 3  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 4  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 5  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 6  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA</code></pre>
<p>We can see that there are six tags with ambiguous detections within this data set. Detections associated with five of the six <code>ambigID</code>s could belong to one of two tags, and detections associated with one <code>ambigID</code> (<code>-171</code>) could belong to one of three tags. The <code>fullID</code> fields list the project names associated with the duplicate tags (e.g., “SampleData”, “Selva”, “Niles”), along with features of the tags (manufacturer tag ID, burst, and transmit frequency).</p>
<p>Let’s get a data frame of these, and do some plots to see where there may be issues.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambigTags</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">ambigID</span>, <span class="va">motusTagID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>newID <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">ambigID</span>, <span class="st">": "</span>, <span class="va">motusTagID</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Using our <code>df.plot</code>, data frame we can filter these detections.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.plot.ambig</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.plot</span>, <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">df.ambigTags</span><span class="op">$</span><span class="va">motusTagID</span><span class="op">)</span></code></pre></div>
<p>Create new ids showing links between ambiguous and non-ambiguous tags.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.plot.ambig</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df.plot.ambig</span>,
                        ambig <span class="op">=</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span>, <span class="co"># Ambiguous or not? TRUE/FALSE</span>
                        newID <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">ambig</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">ambigID</span>, <span class="st">": "</span>, <span class="va">motusTagID</span><span class="op">)</span>, <span class="cn">NA_character_</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<p>Plot the results! We’ll add some information to the plot, showing where (in time) the tags are actually ambiguous. We can then inspect the overall plots (or portions of them) to determine if we can contextually unambiguously assign a detection of an ambiguous tag to a single deployment.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.plot.ambig</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">recvDeployLat</span>, colour <span class="op">=</span> <span class="va">ambig</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">newID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<pre><code>## geom_path: Each group consists of only one observation. Do you need to adjust
## the group aesthetic?</code></pre>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-20-1.png" width="700"></p>
<p>Let’s deal with the easy ones first.</p>
<p><strong>ambigID -337: <code>motusTagID</code>s 10811 and 16011</strong></p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">337</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagDeployStart</span>, <span class="va">tagDeployEnd</span>, <span class="va">tagDepLat</span>, <span class="va">tagDepLon</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 6]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # Groups:   motusTagID, tagDeployStart, tagDeployEnd, tagDepLat
##   motusTagID tagDeployStart tagDeployEnd tagDepLat tagDepLon     n
##        &lt;int&gt;          &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
## 1      10811     1414479600   1438585200      39.1     -74.7     4
## 2      16011     1438515600   1450352400      51.5     -80.4     4</code></pre>
<p>We can see from the plot that ambiguous tag -337 is ambiguous only at the beginning of the deployment.</p>
<p>We can see from the summary of the tag deployment data that there were only 4 detections, at the exact latitude of deployment of tag 16011, and just before the non-ambiguous detections of <code>motusTagID</code> 16011. So the issue here is simply that the tail end of the deployment of tag 10811 slightly overlaps with the deployment of tag 16011. We can confidently claim these detections as belonging to motusTagID 16011, and remove the ambiguous detections assigned to the other tag.</p>
<p>We’ll create another data frame to keep track of these runs.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># we want the detections associated with the motusTagID that we want to </span>
<span class="co"># ultimately REMOVE from the data frame </span>
<span class="va">df.block.2</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">337</span>,
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">10811</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -134: motusTagIDs 22905 and 23319</strong></p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">134</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagDeployStart</span>, <span class="va">tagDeployEnd</span>, 
           <span class="va">tagDepLat</span>, <span class="va">tagDepLon</span>, <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:   lazy query [?? x 7]
## # Database: sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # Groups:   motusTagID, tagDeployStart, tagDeployEnd, tagDepLat, tagDepLon
##   motusTagID tagDeployStart tagDeployEnd tagDepLat tagDepLon `month(ts)`     n
##        &lt;int&gt;          &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;       &lt;int&gt;
## 1      22905     1475337600   1497283200      50.2     -63.7 NA          22279
## 2      23319     1476547200   1498492800      50.2     -63.7 NA          22279</code></pre>
<p>Here we have a similar situation, but one that is a bit more complex. Two identical tags were deployed at the same location, shortly after one another. Let’s examine a simple plot.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.plot</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">22905</span>, <span class="fl">23319</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.plot</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, group <span class="op">=</span> <span class="va">recvDeployName</span>, colour <span class="op">=</span> <span class="va">recvDeployName</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time"</span>, y <span class="op">=</span> <span class="st">"Signal strength"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span><span class="va">recvDeployLon</span> <span class="op">~</span> <span class="va">.</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-23-1.png" width="700"></p>
<p>It appears that these are overlapping detections, at two sites in proximity to one another. Additional information from the field researchers may enable us to disentangle them, but it is not clear from the data.</p>
<p>We will therefore remove all detections of this ambiguous tag from the database. To do so, we collect the motusTagID that we want to remove.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.3</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">134</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -171: motusTagIDs 22778, 22902 and 22403</strong></p>
<p>The ambiguous detections for this tag, which occur in the Great Lakes region, could also belong to <code>motusTagID</code> 22778 from the RBrownAMWO project or <code>motusTagID</code> 24303 from the Neonics project. Let’s take a closer look at these detections.</p>
<p>First, find the deployment dates and locations for each tag.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID tagProjID      start        end      lat       lon
## 1      22902       176 1475337600 1497283200 50.19278 -63.74528
## 2      22778        82 1477008000 1536451200 45.13535 -67.29323
## 3      24303       146 1494455460 1498861860 42.60600 -80.46900
##                 species
## 1              Red Knot
## 2     American Woodcock
## 3 White-crowned Sparrow</code></pre>
<p>And plot the ambiguous detections by date and receiver.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.171</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tbl.alltags.sub</span>, <span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>,
         date <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.171</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">port</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"loess"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="va">date</span> <span class="op">~</span> <span class="va">recvDeployName</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula 'y ~ x'</code></pre>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-26-1.png" width="700"></p>
<p>We see that there are a large number of ambiguous detections on 10 May 2017 at Old Cut (Long Point, Lake Erie, Ontario), consistent with a bird ‘hanging around’. These are almost certainly detections of motusTagID ‘24303’ which was deployed at Old Cut on 10 May 2017. Subsequent detections on the 18th of May are near Old Cut (Bird Studies Canada HQ, Port Rowan, Ontario), and then a location to the North of Old Cut (Hagersville, Ontario). These detections are consistent with a bird departing on migration. Note in particular the pattern in the latter two panels of increasing then decreasing signal strength which indicates a bird is flying through the beam of an antenna.</p>
<p>These detections belong to another project, so we simply remove all detections of that ambiguous tag from our database.</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.4</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -114: motusTagIDs 22897 and 24298</strong></p>
<p>Next we look at the ambiguities for ambiguous tag -114.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:     lazy query [?? x 7]
## # Database:   sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # Ordered by: start
##   motusTagID tagProjID      start        end   lat   lon species              
##        &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                
## 1      22897       176 1475337600 1497283200  50.2 -63.7 Red Knot             
## 2      24298       146 1494385200 1498791600  42.6 -80.5 White-crowned Sparrow</code></pre>
<p>We again subset these and plot them. An initial plot suggested that all of the detections are of a migratory flight, so we construct a somewhat different plot from the one above, that emphasizes this behaviour better.</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.114</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>LatLonStationName <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, sep<span class="op">=</span><span class="st">": "</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.114</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, colour <span class="op">=</span> <span class="va">LatLonStationName</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-29-1.png" width="700"></p>
<p>Notice that the detections are consistent with a migratory departure from the Long Point area (Old Cut Field Station, Lake Erie, Ontario) about a week after the ambiguous tag 24298 was deployed at the same location. This again suggests that these ambiguous detections can be removed from our data because they belong to another project.</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.5</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -106: motusTagIDs 17021 and 17357</strong></p>
<p>These two tags pose an interesting problem. There is only a short period of overlap, between mid August 2015 and mid September. One individual is a Grey-cheeked Thrush, tagged in Colombia, the other a White-rumped Sandpiper, associated with the sample project.</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:     lazy query [?? x 7]
## # Database:   sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # Ordered by: start
##   motusTagID tagProjID      start        end   lat   lon species               
##        &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                 
## 1      17021        57 1430370000 1442206800  11.1 -74.1 Gray-cheeked Thrush   
## 2      17357       176 1439277600 1451114400  51.5 -80.4 White-rumped Sandpiper</code></pre>
<p>We plot the ambiguous detections by date to examine the period of overlap.</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.106</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>,
         date <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.106</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">date</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-32-1.png" width="700"></p>
<p>Both sets of detections are long run lengths, and look valid (increasing then decreasing signal strength). They are about a day apart, and so it is possible they represent two different birds, or the departure flight of the white-rumped sandpiper from its staging ground. Let’s use the <code><a href="../../reference/siteTrans.html">siteTrans()</a></code> function to examine the flight from Netitishi to MDR/Seal (in the Gulf of Maine).</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.106</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">17021</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># just pick one of the two ambiguous IDs</span>
  <span class="fu"><a href="../../reference/siteTrans.html">siteTrans</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rate</span> <span class="op">&lt;</span> <span class="fl">60</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># remove the simultaneous detections from Seal and MDR</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total.time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/period_to_seconds.html">seconds_to_period</a></span><span class="op">(</span><span class="va">tot_ts</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>start <span class="op">=</span> <span class="va">recvDeployName.x</span>, end <span class="op">=</span> <span class="va">recvDeployName.y</span>, 
         date <span class="op">=</span> <span class="va">ts.x</span>, `rate(m/s)` <span class="op">=</span> <span class="va">rate</span>, 
         <span class="va">dist</span>, total.time <span class="op">=</span> <span class="va">total.time</span>, <span class="va">bearing</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   start       end      date                `rate(m/s)`   dist total.time bearing
##   &lt;chr&gt;       &lt;chr&gt;    &lt;dttm&gt;                    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 Netitishi_… MDR_44,… 2015-09-02 04:18:42        17.1 1.21e6      70879    128.</code></pre>
<p>These detections are &gt;1200 km distant from one another, but the flight speed (17 m/s) is consistent with a white-rumped Sandpiper. Given that the Gray-cheeked Thrush tag was near the end of its expected lifetime, we can reasonably claim these detections for our project, and remove the ambiguous detections associated with <code>motusTagID</code> 17021.</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.6</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span>, <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">17021</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -56: motusTagIDs 22867 and 23316</strong></p>
<p>These two tags were also both deployed by the same project.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span></code></pre></div>
<pre><code>## # Source:     lazy query [?? x 7]
## # Database:   sqlite 3.36.0
## #   [/Users/runner/work/motus/motus/vignettes/articles/data/project-176.motus]
## # Ordered by: start
##   motusTagID tagProjID      start        end   lat   lon species           
##        &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;             
## 1      22867       176 1473176100 1495121700  51.8 -80.7 Pectoral Sandpiper
## 2      23316       176 1475424000 1497369600  50.2 -63.7 Red Knot</code></pre>
<p>Tag 23316 was deployed by the James Bay Shorebird Project (sample project) about three weeks after tag 22867, which was deployed from a location far to the west.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.56</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sig <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">sig</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="va">sig</span> <span class="op">*</span> <span class="op">-</span><span class="fl">1</span>, <span class="va">sig</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.56</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">recvDeployLon</span>, y <span class="op">=</span> <span class="va">ts</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, sep<span class="op">=</span><span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name<span class="op">=</span><span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-36-1.png" width="700"></p>
<p>We can see from the plot that a tag is detected consistently near longitude -65, which is near the deployment location for <code>motusTagID</code> 23316 and after it’s deployment start date, it was also present at -65 during and after detections far to the west. It’s likely all the detections at -65 belong to <code>motusTagID</code> 23316, but it is also clear that anything informative about this ambiguity occurs between about 9-11 October, so let’s zoom in on that part of the data set.</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ts.begin</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/ymd_hms.html">ymd_hms</a></span><span class="op">(</span><span class="st">"2016-10-06 00:00:00"</span><span class="op">)</span>
<span class="va">ts.end</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/ymd_hms.html">ymd_hms</a></span><span class="op">(</span><span class="st">"2016-10-12 23:00:00"</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.ambig.56</span>, <span class="va">ts</span> <span class="op">&gt;</span> <span class="va">ts.begin</span>, <span class="va">ts</span> <span class="op">&lt;</span> <span class="va">ts.end</span><span class="op">)</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">recvDeployLon</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-37-1.png" width="700"></p>
<p>We can see that the ambiguous tag was detected consistently at Niapiskau and Grand Ile before and after the period when it was also detected to the north and west (at Washkaugou and Piskwamish) and then to the south (NBNJ, SHNJ, and CONY). We can look at this transition by filtering out the portion of the data not near Niapiskau, and again using the siteTrans function from the <code>motus</code> package.</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># other tag is a duplicate</span>
<span class="va">df.56.tmp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.ambig.56</span>, <span class="op">!</span><span class="op">(</span><span class="va">recvDeployLat</span> <span class="op">==</span> <span class="fl">50.2</span><span class="op">)</span>, <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">22867</span><span class="op">)</span> 

<span class="fu"><a href="../../reference/siteTrans.html">siteTrans</a></span><span class="op">(</span><span class="va">df.56.tmp</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rate</span> <span class="op">&lt;</span> <span class="fl">60</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get rid of simultaneous detections</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total.time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/period_to_seconds.html">seconds_to_period</a></span><span class="op">(</span><span class="va">tot_ts</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>start <span class="op">=</span> <span class="va">recvDeployName.x</span>, 
         end <span class="op">=</span> <span class="va">recvDeployName.y</span>, 
         date <span class="op">=</span> <span class="va">ts.x</span>, `rate(m/s)` <span class="op">=</span> <span class="va">rate</span>, 
         <span class="va">dist</span>, total.time <span class="op">=</span> <span class="va">total.time</span>, <span class="va">bearing</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 11 × 7
##    start     end       date                `rate(m/s)`   dist total.time bearing
##    &lt;chr&gt;     &lt;chr&gt;     &lt;dttm&gt;                    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
##  1 Piskwami… Washkaug… 2016-10-09 22:49:59      20.4   7.68e4       3767   137. 
##  2 Washkaug… SHNJ_40.… 2016-10-10 00:00:42      24.3   1.27e6      52386   157. 
##  3 NBNJ_39.… Niapiska… 2016-10-10 15:47:37       7.74  1.46e6     188426    31.4
##  4 Niapiska… Grand-Il… 2016-10-18 04:22:02      43.5   1.16e4        266   -92.2
##  5 Grand-Il… Niapiska… 2016-10-18 04:29:12       0.728 1.16e4      15887    87.7
##  6 Grand-Il… Niapiska… 2016-10-19 04:34:04       0.531 1.16e4      21758    87.7
##  7 Niapiska… Grand-Il… 2016-10-23 01:39:14       5.55  1.16e4       2084   -92.2
##  8 Grand-Il… Niapiska… 2016-10-25 17:57:52      19.3   1.16e4        600    87.7
##  9 Niapiska… Grand-Il… 2016-10-25 21:13:49       0.243 1.16e4      47541   -92.2
## 10 Grand-Il… Niapiska… 2016-10-26 19:43:34       0.758 1.16e4      15254    87.7
## 11 Niapiska… Grand-Il… 2016-10-27 00:03:21       0.246 1.16e4      46941   -92.2</code></pre>
<p>The bird made a 14.5 hour (52386/60/60) flight between Washkaugou and SHNJ at a rate of 24 m/s, which is plausible. The researchers involved may have other data to support or refute the inference (e.g. an actual sighting of the Red Knot still in Niapiskau after this flight was recorded) but it seems likely that while one tag remained at sites around longitude -65, another tag made the above migratory flights.<br>
We can make another more detailed plot of signal strength to examine these potential migratory flights more closely:</p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.56.tmp</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, <span class="va">recvDeployLon</span> <span class="op">&lt;</span> <span class="op">-</span><span class="fl">70</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>,
         date <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.56.tmp</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvDeployLat</span>, <span class="va">recvDeployLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">date</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-39-1.png" width="700"></p>
<p>These look like typical fly-by patterns of increasing and then decreasing signal strength.<br>
This, coupled with overall detection patterns and knowledge of the species, leads us to believe that the ambiguous detections can be reasonably divided between the two individuals; one detected consistently around longitude -65 (23316), and the other migrating SW during the same period (22867).</p>
<p>To address this problem, we need to create two filters - one that excludes ambiguous detections of tag 22867, and one that excludes some detections of 23316. In this instance, we can do this most easily by filtering on <code>motusTagID</code> and <code>recvDeployName</code>.</p>
<p>Tag 23316 was only ever at “Grand-Ile”, “Niapiskau”, and tag 22867 was never detected at those sites. So we exclude all detections not at “Grand-Ile”, “Niapiskau” for motusTag 23316, and do the opposite for tag 22867.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.7</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, 
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">23316</span>, 
         <span class="op">!</span><span class="op">(</span><span class="va">recvDeployName</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Grand-Ile"</span>, <span class="st">"Niapiskau"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span>

<span class="va">df.block.8</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, 
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">22867</span>, 
         <span class="va">recvDeployName</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Grand-Ile"</span>, <span class="st">"Niapiskau"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
</div>
<div id="checking-validity-of-short-runs" class="section level2">
<h2 class="hasAnchor">
<a href="#checking-validity-of-short-runs" class="anchor"></a>Checking validity of short runs</h2>
<p>At the beginning of this chapter, we removed all short/noisy detections with a <code>motusFilter</code> of 0, because they are considered to have a high probability of being false positive. Now that we’ve cleaned the data, and are confident in the detections that remain, you might at this point decide to go back and take a closer look at those omitted detections. You could do this, for example, by re-running the various plots described in this chapter (begin with lat/lon by time plots), to see if any of those detections make sense in the context of where the true detections lie. It is up to the user to decide which detections are reasonable in terms of the biology and behaviour of each tagged individual.</p>
</div>
<div id="filtering-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#filtering-the-data" class="anchor"></a>Filtering the data</h2>
<div id="filter-and-save-to-rds" class="section level3">
<h3 class="hasAnchor">
<a href="#filter-and-save-to-rds" class="anchor"></a>Filter and save to RDS</h3>
<p>To filter the data, we can omit rows in the <code>df.block</code> data frames from the original data using a <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code>, which removes rows from <code>x</code> (<code>tbl.alltags.sub</code>) which are present in <code>y</code> (<code>df.block</code>).</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># combine our df.block data frames into a single dataframe</span>
<span class="va">df.block.all</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span><span class="va">df.block.0</span>, <span class="va">df.block.2</span>, <span class="va">df.block.3</span>,
                          <span class="va">df.block.4</span>, <span class="va">df.block.5</span>, <span class="va">df.block.6</span>, <span class="va">df.block.7</span>, 
                          <span class="va">df.block.8</span><span class="op">)</span>

<span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">df.block.all</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"runID"</span>, <span class="st">"motusTagID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Now save the local data frame as an RDS file, for use in the next chapter. Recall from <a href="03-accessing-data.html#exporting-detections">Exporting detections in Chapter 3</a> that the RDS format preserves the R data structure, including time stamps. The other benefit of saving to RDS is that you have the output from a given workflow saved as a flat file, which you can access again with a simple <code>readRDS</code> statement.</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">saveRDS</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, file <span class="op">=</span> <span class="st">"./data/dfAlltagsSub.rds"</span><span class="op">)</span></code></pre></div>
<p>And to read the data in again:</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span><span class="op">(</span><span class="st">"./data/dfAlltagsSub.rds"</span><span class="op">)</span></code></pre></div>
</div>
<div id="saveFilter" class="section level3">
<h3 class="hasAnchor">
<a href="#saveFilter" class="anchor"></a>Save a custom filter in the motus database, and apply it to the data</h3>
<p>As an alternative to saving your data as an RDS file, the Motus R package offers functionalities to save your filters directly within your <code>.motus</code> file. Once they are saved in your database, you can do the type of <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code> as above without having to rely on dataframes or an RDS file to store your data. To learn more about the functions available to work with Motus filters, refer to <a href="%7B#appendixD%7D">Appendix D</a> for more details.</p>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.all</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span><span class="va">df.block.0</span>, <span class="va">df.block.2</span>, <span class="va">df.block.3</span>, 
                          <span class="va">df.block.4</span>, <span class="va">df.block.5</span>, <span class="va">df.block.6</span>, <span class="va">df.block.7</span>, 
                          <span class="va">df.block.8</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>probability <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="co"># create a new filter with name filtAmbigFalsePos and populate it with df.block.all</span>
<span class="va">tbl.filter</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/writeRunsFilter.html">writeRunsFilter</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"filtAmbigFalsePos"</span>, 
                              df <span class="op">=</span> <span class="va">df.block.all</span>, delete <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Filter records saved</code></pre>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># obtain a table object where the filtered records from tbl.filter.1 have been removed</span>
<span class="va">tbl.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span>, 
                             <span class="va">tbl.filter</span>, 
                             by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"runID"</span>, <span class="st">"motusTagID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<blockquote>
<p><strong>Next</strong> <a href="06-exploring-data.html">Chapter 6 - Exploring detections data</a></p>
</blockquote>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>In these examples we use the latitude/longitude of the receivers as a proxy for tag location: <code>recvDeployLat</code> and <code>recvDeployLon</code>. However, if your tags have GPS, you may wish to use a more precise lat/lon. See <a href="gps.html">Working with GPS points</a> for more advanced examples with GPS.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by John Brzustowski, Denis LePage, Birds Canada.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
