# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check motus*tar.gz
    
after_failure:
  - ./travis-tool.sh dump_logs