<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Chapter 5 - Data Cleaning • motus</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../../bootstrap-toc.css">
<script src="../../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><meta property="og:title" content="Chapter 5 - Data Cleaning">
<meta property="og:description" content="motus">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">motus</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">4.0.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../articles/articles/motus.html">Get started</a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/articles/01-introduction.html">Chapter 1 - Introduction</a>
    </li>
    <li>
      <a href="../../articles/articles/02-installing-packages.html">Chapter 2 - Installing packages</a>
    </li>
    <li>
      <a href="../../articles/articles/03-accessing-data.html">Chapter 3 - Accessing detections data</a>
    </li>
    <li>
      <a href="../../articles/articles/04-deployments.html">Chapter 4 - Tag and receiver deployments</a>
    </li>
    <li>
      <a href="../../articles/articles/05-data-cleaning.html">Chapter 5 - Data Cleaning</a>
    </li>
    <li>
      <a href="../../articles/articles/06-exploring-data.html">Chapter 6 - Exploring detections data</a>
    </li>
    <li class="divider">
    <li>
      <a href="../../articles/index.html">More...</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="05-data-cleaning_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Chapter 5 - Data Cleaning</h1>
                        <h4 class="author">Tara L. Crewe, Zoe Crysler, and Philip Taylor. Revisions by Catherine Jardine, Steffi LaZerte and Denis Lepage</h4>
            
      
      
      <div class="hidden name"><code>05-data-cleaning.Rmd</code></div>

    </div>

    
    
<p>There are three sources of ‘error’ that can result in tag detections appearing in your database that are incorrect.</p>
<p>First, random radio noise (‘static’) can be detected and interpreted to be the transmission of a tag. These are called ‘false positives’.</p>
<p>Second, despite our best efforts to avoid it, duplicate tags are sometimes transmitting in the network at the same time. When two tags are deployed at the same time that have the same ID code, burst interval, and nominal transmit frequency, it results in situations where the detections may belong to either tag. If that happens, we must rely on contextual information to separate them (if we can). We term these ‘Ambiguous tags’.</p>
<p>Third, a tag can appear to be present when two tags are transmitting at the same time that by chance produce a signal that looks like a third tag that is not in fact present. Such tags are most common at roosting sites or breeding colonies, where many tags are transmitting simultaneously. We term these ‘Aliased tags’. We do not deal explicitly with Aliased tags in this chapter; we are working on a way to globally identify them and eliminate them from the data. We mention them here because you may encounter situations with what appear to be highly plausible detections that don’t make biological sense. Please contact us if you think you have some of these Aliased tag detections in your database.</p>
<p>The <em>goal of this chapter</em> is to provide you with the tools you need to check your data for false detections, and remove them from your data. We do so by providing example workflows that deal with ‘false positives’ and ‘ambiguous tags’ in the following steps:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Run a preliminary filter to remove all detections with <code>runLen</code> of 3 or less, and detections with intermediate <code>runLen</code>s made during periods of high noise/activity.</strong><br>
A run is a group of consecutive detections of a tag detected on a single antenna at a single receiver. In general, a detection with a run length of 2 or 3 (i.e., 2 or 3 bursts) has a high probability of being a false positive detection. With the exception of a few ‘quiet’ stations with little noise, we generally recommend that you filter out all detections with a run length of 3 or less. However, because you will likely lose some true detections in the process, we also recommend that after a full analysis of your data, you return to these detections and examine them individually, to determine (usually contextually) if they can be considered real. Stations that are particularly noisy may also have false detections with longer <code>runLen</code>s.</p></li>
<li><p><strong>Determine how many of your tag detections may be ambiguous detections</strong></p></li>
<li><p><strong>Provide a workflow for examining individual tags, and determine if runs in those tags are errors</strong></p></li>
<li><p><strong>Filter errors from your data</strong></p></li>
</ol>
<div id="load-required-packages" class="section level2">
<h2 class="hasAnchor">
<a href="#load-required-packages" class="anchor"></a>Load required packages</h2>
<p>Follow the instructions in <a href="02-installing-packages.html">Chapter 2</a> to install the following packages before loading, if they are not already installed.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">motus</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://lubridate.tidyverse.org">lubridate</a></span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/Sys.setenv.html">Sys.setenv</a></span><span class="op">(</span>tz <span class="op">=</span> <span class="st">"UTC"</span><span class="op">)</span></code></pre></div>
</div>
<div id="load-detections-data" class="section level2">
<h2 class="hasAnchor">
<a href="#load-detections-data" class="anchor"></a>Load detections data</h2>
<p>Recall from <a href="03-accessing-data.html#user-authentication">Chapter 3</a> that when accessing the sample database, you will need to input <code>motus.sample</code> in the R console as both username and password when prompted by the <code><a href="../../reference/tagme.html">tagme()</a></code> user authentication process. This section assumes you have already completed the <a href="03-accessing-data.html#downloading-tag-detections">initial sample data download</a>.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sql.motus</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/tagme.html">tagme</a></span><span class="op">(</span><span class="fl">176</span>, update <span class="op">=</span> <span class="cn">TRUE</span>, dir <span class="op">=</span> <span class="st">"./data/"</span><span class="op">)</span></code></pre></div>
<pre><code>## Checking for new data in project 176</code></pre>
<pre><code>## activity:     0 new batch records to check</code></pre>
<pre><code>## nodeData:     0 new batch records to check</code></pre>
</div>
<div id="assess-tag-detections" class="section level2">
<h2 class="hasAnchor">
<a href="#assess-tag-detections" class="anchor"></a>Assess tag detections</h2>
<p>First, determine which project tags have detections. There are several reasons why deployed tags might not be detected, including:</p>
<ol style="list-style-type: decimal">
<li><p>The tag was not properly activated on deployment. To avoid this, always check that a tag is active using a hand-held receiver before attaching the tag to your study animal and releasing it.</p></li>
<li><p>An animal with a properly activated tag might not have passed within range of a receiving station. Study designs that incorporate strategic placement of receivers to meet project goals can improve the probability of a tag being detected.</p></li>
<li><p>Missing or incorrect tag deployment metadata in the Motus database can result in the data processing algorithm not ‘looking’ for your tag at the time the tag was deployed, or at all. Please ensure your tag metadata are entered correctly.</p></li>
</ol>
<p>Before going further, <strong>please check whether any of your tags were deployed more than once</strong>, as described in section @ref(checkNumberTagDeployments). If so, you will need to use <code>tagDeployID</code> or a combination of <code>motusTagID</code> and <code>tagDeployID</code> to uniquely define detections associated with a tag deployment (either will do, but combining the two fields will let you know which tagID is associated with each deployment).</p>
<p>In the sample data, all tags were deployed only once, and so we use the <code>motusTagID</code> as a unique identifier for a tag deployment in all R code throughout the book.</p>
<p>Using the <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> function we can see that there are detections for 18 tags deployed by the sample project.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tagProjID</span> <span class="op">==</span> <span class="fl">176</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># subset to include only tags registered to project</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##    motusTagID     n
## 1       16011   127
## 2       16035   456
## 3       16036   118
## 4       16037  1353
## 5       16038   162
## 6       16039  1126
## 7       16044   305
## 8       16047   839
## 9       16048    98
## 10      16052   159
## 11      17357   289
## 12      19129  1936
## 13      22867  5767
## 14      22897 34796
## 15      22902  2923
## 16      22905 26010
## 17      23316  5734
## 18      23319 22759</code></pre>
<p>If we break down these counts by run length using the following code we further see that many have run lengths of 3 (the <code>run 3</code> column).</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tagProjID</span> <span class="op">==</span> <span class="fl">176</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># subset to include only tags registered to project</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>rl.gt.3 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">runLen</span> <span class="op">==</span> <span class="fl">3</span>, <span class="st">"run 3"</span>, <span class="st">"run &gt; 3"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">rl.gt.3</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/spread.html">spread</a></span><span class="op">(</span>key <span class="op">=</span> <span class="va">rl.gt.3</span>, value <span class="op">=</span> <span class="va">n</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 18 × 3
## # Groups:   motusTagID [18]
##    motusTagID `run &gt; 3` `run 3`
##         &lt;int&gt;     &lt;int&gt;   &lt;int&gt;
##  1      16011       118       9
##  2      16035       441      15
##  3      16036       115       3
##  4      16037      1335      18
##  5      16038       156       6
##  6      16039      1117       9
##  7      16044       287      18
##  8      16047       758      81
##  9      16048        83      15
## 10      16052       144      15
## 11      17357       286       3
## 12      19129      1801     135
## 13      22867      5572     195
## 14      22897     34373     423
## 15      22902      2854      69
## 16      22905     25782     228
## 17      23316      5551     183
## 18      23319     22567     192</code></pre>
<p>Although some of these may be valid detections, we have found it simpler to just remove them from our analysis, and possibly revisit them at a later stage. In the next few sections we will explore a series of filters that do just this.</p>
</div>
<div id="preliminary-filtering" class="section level2">
<h2 class="hasAnchor">
<a href="#preliminary-filtering" class="anchor"></a>Preliminary filtering</h2>
<p>We can perform some preliminary filtering based on run length (<code>runLen</code>). As runs are composed of sequences of hits, the longer the run the more confident we can be that it represents a true detection. However, local conditions at an individual receiver may vary in their exposure to background radio noise. Sites with relatively more background noise may be more prone to reporting false detections. Therefore the standard motus filter relies both on the length of the run, and the amount of radio activity at a given site. This value is stored as a field called <code>motusFilter</code> in the <code>runs</code> table. An additional table (<code>activity</code>) allows users to calculate a filter based on different criteria if they want.</p>
<div id="understanding-the-motusfilter" class="section level3">
<h3 class="hasAnchor">
<a href="#understanding-the-motusfilter" class="anchor"></a>Understanding the <code>motusFilter</code>
</h3>
<p>Starting in July 2019, data downloaded from motus with the <code><a href="../../reference/tagme.html">tagme()</a></code> function will include a standard filter value that can be used to identify detections that we believe have a higher probability of being false hits. The various outputs on the motus web site are pre-filtered, but the R package provides access to all detections, allowing users more control over which detections to keep or omit. The <code>motusFilter</code> field in the <code>runs</code> table represents the probability that the run is a true detection. Currently the <code>motusFilter</code> contains just two values <code>0</code> or <code>1</code>. Runs with a <code>motusFilter</code> of <code>0</code> have a low probability of being true detections.</p>
</div>
<div id="how-the-motusfilter-is-generated" class="section level3">
<h3 class="hasAnchor">
<a href="#how-the-motusfilter-is-generated" class="anchor"></a>How the <code>motusFilter</code> is generated</h3>
<p>The <code>motusFilter</code> is based the number of detections of different run lengths at a given site, across all motus projects. Periods with lots of radio interference will typically generate a high number of very short runs that are in reality spurious data. In the presence of a high ratio of runs with length = 2 at a given time, we consider that site as ‘noisy’ and increase the minimum threshold for run lengths that we consider to be valid detections.</p>
<p>In general, a detection with a run length of 2 or 3 (i.e., 2 or 3 bursts) has a relatively high probability of being a false positive detection. Therefore, runs with a length 3 or less are conservatively assigned a <code>motusFilter</code> of 0. For runs greater than length 3, data in the <code>activity</code> table provides a method of assessing the relative amount of background noise at a site which can be used to assess the probability of these runs being true detections. The <code>activity</code> table provides the number of runs of various lengths for each hour (called <code>hourBin</code>) within each batch and for each antenna. A high number of detections within an hour (e.g., &gt;= 100) with a high proportion of short runs (e.g., length 2 &gt;= 85%) are indicative of a noisy environment, more likely to generate false positives. For those periods, we treat the intermediate run lengths (3 &lt; <code>runLen</code> &lt; 5) as invalid (<code>motusFilter</code> = 0). Intermediate run lengths are otherwise considered valid (<code>motusFilter</code> = 1).</p>
<p>The <code>motusFilter</code> values in the <code>runs</code> table have been calculated on the basis of the above criteria, which were determined through some empirical examination of data. If you are working with a dataset downloaded through <code><a href="../../reference/tagme.html">tagme()</a></code> prior to July 2019 it will not include those values. In those cases, you will either need to download a new copy of the entire dataset for your project or receiver, or to use the <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function described below to calculate the missing values.</p>
<p>To omit runs identified as dubious by <code>motusFilter</code> we can use an anti-join.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Number of rows with runs 3 hits or less</span>
<span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span>, <span class="va">runLen</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 83147</code></pre>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Identify runs to remove</span>
<span class="va">to_remove</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"runs"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">runID</span>, <span class="va">motusFilter</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusFilter</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>

<span class="co"># Use anti-join to remove those runs from the alltags</span>
<span class="va">tbl_filtered</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/tbl.html">tbl</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"alltags"</span><span class="op">)</span>, <span class="va">to_remove</span>, by <span class="op">=</span> <span class="st">"runID"</span><span class="op">)</span>

<span class="co"># Number of rows with runs 3 hits or less after being filtered</span>
<span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tbl_filtered</span>, <span class="va">runLen</span> <span class="op">&lt;=</span> <span class="fl">3</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
<div id="custom-filters-with-the-filterbyactivity-function" class="section level3">
<h3 class="hasAnchor">
<a href="#custom-filters-with-the-filterbyactivity-function" class="anchor"></a>Custom filters with the <code>filterByActivity()</code> function</h3>
<p>The <code>motusFilter</code> is one method of determining false detections, but motus users are encouraged to explore alternative filter parameters. The <code>motus</code> R-package includes a <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function that allows users to specify custom parameters used to identify false positives based on the <code>activity</code> table. Users can return either just the “true” positives (<code>return = "good"</code>), just the “false” positives (<code>return = "bad"</code>) or all hits (<code>return = "all"</code>) but with a new column, “probability”, which reflects either 0 (expected false positive) or 1 (expected true positive).</p>
<p>For example, the following code, adds a <code>probability</code> column to the sample project data, which is identical to the <code>motusFilter</code> column (i.e., by default <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> uses the same conditions).</p>
<p><strong>Note</strong> that this function requires the SQLite database connection (not a flat data frame), but returns a data.frame of the <code>alltags</code> view (not a SQLite database connection).</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl_motusFilter</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/filterByActivity.html">filterByActivity</a></span><span class="op">(</span><span class="va">sql.motus</span>, return <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span></code></pre></div>
<p>Users can adjust these parameters to be less strict (i.e., exclude fewer detections). This example excludes all runs of length 2 or less and will exclude any runs less than length 4 from <code>hourBin</code>s which have more than 500 runs and where at least 95% of those runs have a run length of 2.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl_relaxed</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/filterByActivity.html">filterByActivity</a></span><span class="op">(</span><span class="va">sql.motus</span>, minLen <span class="op">=</span> <span class="fl">2</span>, maxLen <span class="op">=</span> <span class="fl">4</span>, 
                                maxRuns <span class="op">=</span> <span class="fl">500</span>, ratio <span class="op">=</span> <span class="fl">0.95</span>, return <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span></code></pre></div>
<p>These parameters can also be more strict (i.e., exclude more detections). This next example excludes all runs of length 4 or less and will exclude any runs less than length 10 from <code>hourBin</code>s which have more than 50 runs and where at least 75% of those runs have a run length of 2.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl_strict</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/filterByActivity.html">filterByActivity</a></span><span class="op">(</span><span class="va">sql.motus</span>, minLen <span class="op">=</span> <span class="fl">4</span>, maxLen <span class="op">=</span> <span class="fl">10</span>, 
                               maxRuns <span class="op">=</span> <span class="fl">50</span>, ratio <span class="op">=</span> <span class="fl">0.75</span>, return <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span></code></pre></div>
<p>Note that the filters may exclude some true detections in the process. Therefore, we recommend that after a full analysis of your data, you return to these detections and examine them individually, to determine (usually contextually) if they can be considered real.</p>
</div>
</div>
<div id="preparing-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#preparing-the-data" class="anchor"></a>Preparing the data</h2>
<p>When accessing the <code>alltags</code> view, we filter the data and remove some unnecessary variables to reduce the overall size of the data set and make it easier to work with. <strong>This is particularly important for large, unwieldy projects</strong>; details on how to view the variables in a <code>tbl</code>, and how to filter and subset prior to collecting data into a dataframe can be found in Chapter @ref(convertToFlat).</p>
<div id="label-detections-by-probability" class="section level3">
<h3 class="hasAnchor">
<a href="#label-detections-by-probability" class="anchor"></a>Label detections by probability</h3>
<p>First we will use the <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function to label dubious detections. This returns all the data in the <code>alltags</code> view with a new <code>probability</code> column.</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/filterByActivity.html">filterByActivity</a></span><span class="op">(</span><span class="va">sql.motus</span>, return <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span></code></pre></div>
<p>Alternatively we can change the default, so the <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function uses the <code>alltagsGPS</code> view. <strong>However,</strong> on very large databases this could be slow.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">tbl.alltags.gps</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/filterByActivity.html">filterByActivity</a></span><span class="op">(</span><span class="va">sql.motus</span>, return <span class="op">=</span> <span class="st">"all"</span>, view <span class="op">=</span> <span class="st">"alltagsGPS"</span><span class="op">)</span></code></pre></div>
</div>
<div id="clean-up" class="section level3">
<h3 class="hasAnchor">
<a href="#clean-up" class="anchor"></a>Clean up</h3>
<p>Let’s filter to the ‘good’ detections. We will filter to <code>1</code> for detections to keep and <code>0</code> for dubious detections. Then we’ll use the <code><a href="https://dplyr.tidyverse.org/reference/compute.html">collect()</a></code> and <code><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame()</a></code> functions to transform the dataframe into a ‘flat’ (i.e. non SQLite) file, and then transform all time stamp variables from seconds since January 1 1970 to datetime (POSIXct) format.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="va">tbl.alltags</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">probability</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ts <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>,  <span class="co"># work with dates AFTER transforming to flat file</span>
         tagDeployStart <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span>,
         tagDeployEnd <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_datetime</a></span><span class="op">(</span><span class="va">tagDeployEnd</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Let us also save the excluded detections for later analysis.</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tbl.alltags</span>, <span class="va">probability</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
</div>
<div id="add-gps-data" class="section level3">
<h3 class="hasAnchor">
<a href="#add-gps-data" class="anchor"></a>Add GPS data</h3>
<p>The <code><a href="../../reference/filterByActivity.html">filterByActivity()</a></code> function can use the <code>alltagsGPS</code> view, but this may be slow. A way around this speed problem is to use the <code><a href="../../reference/getGPS.html">getGPS()</a></code> function to retrieve the GPS values of a data subset (<code>data</code>) after the data has been filtered.</p>
<blockquote>
<p>Note that in this example, the sample dataset doesn’t have GPS data</p>
</blockquote>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Retrieve GPS data for each hitID</span>
<span class="va">gps_index</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/getGPS.html">getGPS</a></span><span class="op">(</span><span class="va">sql.motus</span>, data <span class="op">=</span> <span class="va">df.alltags.sub</span>, by <span class="op">=</span> <span class="st">"closest"</span><span class="op">)</span>

<span class="co"># Merge GPS points in with our data</span>
<span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, <span class="va">gps_index</span>, by <span class="op">=</span> <span class="st">"hitID"</span><span class="op">)</span></code></pre></div>
<p>We match GPS locations to <code>hitID</code>s according to one of several different time values, specified by the <code>by</code> argument. This can be the <code>closest</code> location in time, the <code>daily</code> median location, or the median location within <code>X</code> minutes of a <code>hitID</code> (here, <code>X</code> can be any number greater than zero and represents the size of the time block in minutes over which to calculate a median location). If using the <code>closest</code> option, you can also specify a <code>cutoff</code> which will only match GPS records which are within <code>cutoff = X</code> minutes of the hit. This way you can avoid having situations where the ‘closest’ GPS record is actually days away (see also Chapter @ref(addGPS)).</p>
<p>We then create receiver latitude and longitude variables (<code>recvLat</code>, <code>recvLon</code>, <code>recvAlt</code>) based on the coordinates recorded by the receiver GPS (<code>gpsLat</code>, <code>gpsLon</code>, <code>gpsAlt</code>), and where those are not available, infilled with coordinates from the receiver deployment metadata (<code>recvDeployLat</code>, <code>recvDeployLon</code>, <code>recvDeployAlt</code>). Missing GPS coordinates may appear as <code>NA</code> if they are missing, or as <code>0</code> or <code>999</code> if there was a problem with the unit recording.</p>
<p>Finally, we create ‘receiver names’ by adding rounded <code>recvLat</code> and <code>recvLon</code> to the <code>recvDeployName</code> for those receivers in the database that do not have these values filled in. As more users explore (and fix!) their metadata, these missing values should begin to disappear. We’ll fix this here as sometimes if there is missing metadata (ie. a missing receiver deployment spanning some of your detections), you will get <code>NA</code>s which can lead to problems later on.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>recvLat <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">gpsLat</span><span class="op">)</span><span class="op">|</span><span class="va">gpsLat</span> <span class="op">==</span> <span class="fl">0</span><span class="op">|</span><span class="va">gpsLat</span> <span class="op">==</span> <span class="fl">999</span><span class="op">)</span>, 
                           <span class="va">recvDeployLat</span>, <span class="va">gpsLat</span><span class="op">)</span>,
         recvLon <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">gpsLon</span><span class="op">)</span><span class="op">|</span><span class="va">gpsLon</span> <span class="op">==</span> <span class="fl">0</span><span class="op">|</span><span class="va">gpsLon</span> <span class="op">==</span> <span class="fl">999</span><span class="op">)</span>, 
                           <span class="va">recvDeployLon</span>, <span class="va">gpsLon</span><span class="op">)</span>,
         recvAlt <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">gpsAlt</span><span class="op">)</span>, <span class="va">recvDeployAlt</span>, <span class="va">gpsAlt</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">noise</span>, <span class="op">-</span><span class="va">slop</span>, <span class="op">-</span><span class="va">burstSlop</span>, <span class="op">-</span><span class="va">done</span>, <span class="op">-</span><span class="va">bootnum</span>, <span class="op">-</span><span class="va">mfgID</span>, 
         <span class="op">-</span><span class="va">codeSet</span>, <span class="op">-</span><span class="va">mfg</span>, <span class="op">-</span><span class="va">nomFreq</span>, <span class="op">-</span><span class="va">markerNumber</span>, <span class="op">-</span><span class="va">markerType</span>, 
         <span class="op">-</span><span class="va">tagDepComments</span>, <span class="op">-</span><span class="va">fullID</span>, <span class="op">-</span><span class="va">deviceID</span>, <span class="op">-</span><span class="va">recvDeployLat</span>, 
         <span class="op">-</span><span class="va">recvDeployLon</span>, <span class="op">-</span><span class="va">recvDeployAlt</span>, <span class="op">-</span><span class="va">speciesGroup</span>, <span class="op">-</span><span class="va">gpsLat</span>, 
         <span class="op">-</span><span class="va">gpsLon</span>, <span class="op">-</span><span class="va">recvAlt</span>, <span class="op">-</span><span class="va">recvSiteName</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>recvLat <span class="op">=</span> <span class="fu">plyr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/plyr/man/round_any.html">round_any</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="fl">0.05</span><span class="op">)</span>, 
         recvLon <span class="op">=</span> <span class="fu">plyr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/plyr/man/round_any.html">round_any</a></span><span class="op">(</span><span class="va">recvLon</span>, <span class="fl">0.05</span><span class="op">)</span>,
         recvDeployName <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvDeployName</span><span class="op">)</span>, 
                                  <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, sep<span class="op">=</span><span class="st">":"</span><span class="op">)</span>, 
                                  <span class="va">recvDeployName</span><span class="op">)</span><span class="op">)</span>

<span class="co"># Note that in the select statement, you can just select the variables you need</span>
<span class="co"># e.g.: select(runID, ts, sig, freqsd, motusTagID, ambigID, runLen, tagProjID, </span>
<span class="co">#              tagDeployStart, tagDeployEnd, etc.)</span>
<span class="co"># As opposed to those you don't need (-done, -bootnum, etc.)</span></code></pre></div>
<p>Now we have a nice clean data frame!</p>
</div>
</div>
<div id="preliminary-data-checks" class="section level2">
<h2 class="hasAnchor">
<a href="#preliminary-data-checks" class="anchor"></a>Preliminary data checks</h2>
<p>Prior to more specific filtering the data, we will perform a few summaries and plots of the data.</p>
<div id="summarize-tag-detections" class="section level3">
<h3 class="hasAnchor">
<a href="#summarize-tag-detections" class="anchor"></a>Summarize tag detections</h3>
<p>An initial view of the data is best achieved by plotting. We will show you later how to plot detections on a map, but we prefer a simpler approach first; plotting detections through time by both latitude and longitude. First however, we should simplify the data. If we don’t, we risk trying to plot thousands or millions of points on a plot (which can take a long time). We’ll do this by creating a little function here, since we will use this operation again in future steps.</p>
<p>Note that we will need to remove about 150 detections, because there is no geographic data associated with the receiver metadata, and so no way to determine the location of those detections. Do a simple check to see if these receivers belong to you, and if so, please <strong>fix the metadata online</strong>!</p>
<p>For example, here we can see which receivers are missing (<code>is.na(recvLat)</code>).</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvLat</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, <span class="va">recvDeployID</span>, <span class="va">recv</span>, 
         <span class="va">recvProjID</span>, <span class="va">recvProjName</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   recvLat recvLon recvDeployName recvDeployID            recv recvProjID
## 1      NA      NA      NP mobile         3813       Lotek-280        176
## 2      NA      NA          NA:NA           NA SG-1415BBBK0382         NA
## 3      NA      NA          NA:NA           NA SG-2814BBBK0547         NA
##   recvProjName
## 1   SampleData
## 2         &lt;NA&gt;
## 3         &lt;NA&gt;</code></pre>
<p><strong>Simplify the data for plotting</strong></p>
<p>We can simplify the data by summarizing by the <code>runID</code>. If you want to summarize at a finer/coarser scale, you can also create other groups. The simplest alternative is a rounded timestamp variable; for example by using <code>mutate(ts.h = plyr::round_any(ts, 3600)</code>. Other options are to just use date (e.g <code>date = as_date(ts)</code>).</p>
<p>Here is an advanced example creating a function so we can re-use this simplification later.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fun.getpath</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">df</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">tagProjID</span> <span class="op">==</span> <span class="fl">176</span>, <span class="co"># keep only tags registered to the sample project</span>
           <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">recvLat</span><span class="op">)</span> <span class="op">|</span> <span class="op">!</span><span class="op">(</span><span class="va">recvLat</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># drops data without lon/lat</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span>, <span class="va">recvDeployName</span>, <span class="va">ambigID</span>, 
             <span class="va">tagDepLon</span>, <span class="va">tagDepLat</span>, <span class="va">recvLat</span>, <span class="va">recvLon</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
    <span class="co">#summarizing by runID to get max run length and mean time stamp:</span>
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>max.runLen <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">runLen</span><span class="op">)</span>, ts.h <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">ts.h</span><span class="op">)</span>
<span class="op">}</span> <span class="co"># end of function</span>

<span class="va">df.alltags.path</span> <span class="op">&lt;-</span> <span class="fu">fun.getpath</span><span class="op">(</span><span class="va">df.alltags.sub</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'motusTagID', 'runID', 'recvDeployName', 'ambigID', 'tagDepLon', 'tagDepLat', 'recvLat'. You can override using the `.groups` argument.</code></pre>
<p>We would initially plot a subset of tags by either latitude or longitude, to get an overview of where there might be issues. Here, to simplify the example, we plot only six tags. We avoid examining the ambiguous tags for now.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.path</span>, 
                     <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16011</span>, <span class="fl">16035</span>, <span class="fl">16036</span>, <span class="fl">16037</span>, <span class="fl">16038</span>, <span class="fl">16039</span><span class="op">)</span><span class="op">)</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts.h</span>, y <span class="op">=</span> <span class="va">recvLat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">motusTagID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-17-1.png" width="700"></p>
<p>Although there don’t seem to be any immediate problems, let’s take a look at the tags showing up around 44 degrees during September. Let’s examine these tags in more detail by examining the runs in the data frame that are associated with detections in September.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9</span><span class="op">)</span>,
         <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16035</span>, <span class="fl">16037</span>, <span class="fl">16039</span><span class="op">)</span>,
         <span class="va">recvLat</span> <span class="op">&lt;</span> <span class="fl">44</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">recvDeployName</span>, <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, <span class="va">runLen</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, 
            n.tags <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">motusTagID</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">runLen</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'recvDeployName', 'month(ts)'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 13 × 5
## # Groups:   recvDeployName, month(ts) [5]
##    recvDeployName        `month(ts)` runLen     n n.tags
##    &lt;chr&gt;                       &lt;dbl&gt;  &lt;int&gt; &lt;int&gt;  &lt;int&gt;
##  1 Assateague State Park           9      6     6      1
##  2 FINWR                           9      6     6      1
##  3 FINWR                           9     10    10      1
##  4 FINWR                           9     20    20      1
##  5 Prime Hook                      9     23    23      1
##  6 BULL                            9     24    24      1
##  7 Prime Hook                      9     27    27      1
##  8 Bombay Hook                     9     32    32      1
##  9 Prime Hook                      9     32    32      1
## 10 Bombay Hook                     9     36    36      1
## 11 BULL                            9     38    38      1
## 12 Bombay Hook                     9     53    53      1
## 13 FINWR                           9     73    73      1</code></pre>
<p>Since we have already filtered dubious detections, these remaining ones don’t seem immediately unreliable (all with runs of at least 6). If you are interested, you can re-run the code above, but on the full data frame (<code>tbl(sql.motus, "alltags")</code>) containing run lengths of 2 or 3. You will see that there are likely false positive detections at these sites, that were already eliminated by filtering. These additional detections provide further evidence that these sites experienced some radio noise during these particular months, resulting in some false positive detections.</p>
<p>You may also be interested more generally in exploring which data have only short run lengths. For example, the following code shows the maximum run length at all sites by month (for those runs which haven’t been removed by filtering).</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">recvDeployName</span>, <span class="va">month</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>max.rl <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">runLen</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/spread.html">spread</a></span><span class="op">(</span>key <span class="op">=</span> <span class="va">month</span>, value <span class="op">=</span> <span class="va">max.rl</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'recvDeployName'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 43 × 8
## # Groups:   recvDeployName [43]
##    recvDeployName          `2`   `3`   `4`   `5`   `8`   `9`  `10`
##    &lt;chr&gt;                 &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 Assateague State Park    NA    NA    NA    NA    NA     6    NA
##  2 BennettMeadow            NA    NA    NA    NA    NA    NA    11
##  3 BISE                     NA    NA    NA    NA    NA    NA     6
##  4 Bombay Hook              NA    NA    NA    NA    NA    53    NA
##  5 Brier2                   NA    NA    NA    NA    NA    29    NA
##  6 BSC HQ                   NA    NA    NA    21    NA    NA    NA
##  7 BULL                     NA    NA    NA    NA    NA    38     5
##  8 Comeau (Marshalltown)    NA    NA    NA    NA    NA     4    NA
##  9 CONY                     NA    NA    NA    NA    NA    NA     7
## 10 D'Estimauville           NA    NA    NA    NA    NA    40    NA
## # … with 33 more rows</code></pre>
<p>Alternatively, you can produce a list of sites where the maximum run length of detections was never greater than (say) 4, which may sometimes (but not always!) indicate they are simply false detections.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>month <span class="op">=</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">recvDeployName</span>, <span class="va">month</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>max.rl <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">runLen</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">max.rl</span> <span class="op">&lt;</span> <span class="fl">5</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/spread.html">spread</a></span><span class="op">(</span>key <span class="op">=</span> <span class="va">month</span>, value <span class="op">=</span> <span class="va">max.rl</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'recvDeployName'. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 3 × 4
## # Groups:   recvDeployName [3]
##   recvDeployName          `4`   `9`  `10`
##   &lt;chr&gt;                 &lt;int&gt; &lt;int&gt; &lt;int&gt;
## 1 Comeau (Marshalltown)    NA     4    NA
## 2 Old Cut                   4    NA    NA
## 3 TRUS                     NA    NA     4</code></pre>
<p>It is impossible to go through every possible issue that you may encounter here. Users are strongly encouraged to explore their data fully, and make reasoned decisions on which detections are unlikely or indeterminate. Through the rest of this chapter we will show you how to collect these runs, and apply them to your data prior to analysis.</p>
<p>To start, if we decided that those detections in September were false positives, we could create a data frame that contains the <code>motusTagID</code>s and <code>runID</code>s for them.</p>
<p>We could then re-create the plot with the newly filtered data.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Collect dubious detections</span>
<span class="va">df.block.1</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fl">9</span>,
         <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16035</span>, <span class="fl">16037</span>, <span class="fl">16039</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span>

<span class="co"># use the function we created earlier to make a new 'path' data frame for plotting</span>
<span class="va">df.alltags.path</span> <span class="op">&lt;-</span> <span class="fu">fun.getpath</span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, 
                                      <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">16011</span>, <span class="fl">16035</span>, <span class="fl">16036</span>, 
                                                        <span class="fl">16037</span>, <span class="fl">16038</span>, <span class="fl">16039</span><span class="op">)</span>, 
                                      <span class="op">!</span><span class="op">(</span><span class="va">runID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">df.block.1</span><span class="op">$</span><span class="va">runID</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'motusTagID', 'runID', 'recvDeployName', 'ambigID', 'tagDepLon', 'tagDepLat', 'recvLat'. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.alltags.path</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts.h</span>, y <span class="op">=</span> <span class="va">recvLat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">motusTagID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-21-1.png" width="700"></p>
<p>The reader is encouraged to explore the rest of the tags within this group, to determine if there are additional false positives.</p>
</div>
</div>
<div id="examining-ambiguous-detections" class="section level2">
<h2 class="hasAnchor">
<a href="#examining-ambiguous-detections" class="anchor"></a>Examining ambiguous detections</h2>
<p>Before we go further, we need to check to see if any tags have ambiguous detections. If there are, we will need to explore them, and create additional filters to remove detections from our database.</p>
<p><strong>Are any of your tags associated with ambiguous detections?</strong></p>
<p>The <code><a href="../../reference/clarify.html">clarify()</a></code> function in the <code>motus</code> R package provides a summary of ambiguities in the detections data. Each <code>ambigID</code> refers to a selection of detections that could belong to one or more (up to 6) <code>motusTagID</code>s, which are listed in the <code>id1</code> to <code>id6</code> columns:</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/clarify.html">clarify</a></span><span class="op">(</span><span class="va">sql.motus</span><span class="op">)</span></code></pre></div>
<pre><code>##   ambigID numHits   id1                              fullID1   id2
## 1     -56    5734 22867 SampleData#272.1:5.3@166.38(M.22867) 23316
## 2    -106     279 17021        Selva#172:6.1@166.38(M.17021) 17357
## 3    -114      86 22897 SampleData#303.1:5.3@166.38(M.22897) 24298
## 4    -134   22749 22905   SampleData#301:5.3@166.38(M.22905) 23319
## 5    -171    2074 22778   RBrownAMWO#308:5.3@166.38(M.22778) 22902
## 6    -337       4 10811        Niles#152:6.1@166.38(M.10811) 16011
##                                fullID2   id3                         fullID3
## 1   SampleData#272:5.3@166.38(M.23316)    NA                            &lt;NA&gt;
## 2   SampleData#172:6.1@166.38(M.17357)    NA                            &lt;NA&gt;
## 3      NEONICS#303:5.3@166.38(M.24298)    NA                            &lt;NA&gt;
## 4 SampleData#301.1:5.3@166.38(M.23319)    NA                            &lt;NA&gt;
## 5 SampleData#308.1:5.3@166.38(M.22902) 24303 NEONICS#308:5.3@166.38(M.24303)
## 6   SampleData#152:6.1@166.38(M.16011)    NA                            &lt;NA&gt;
##   id4 fullID4 id5 fullID5 id6 fullID6 motusTagID tsStart tsEnd
## 1  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 2  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 3  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 4  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 5  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA
## 6  NA    &lt;NA&gt;  NA    &lt;NA&gt;  NA    &lt;NA&gt;         NA      NA    NA</code></pre>
<p>We can see that there are six tags with ambiguous detections within this data set. Detections associated with five of the six <code>ambigID</code>s could belong to one of two tags, and detections associated with one <code>ambigID</code> (<code>-171</code>) could belong to one of three tags. The <code>fullID</code> fields list the project names associated with the duplicate tags (e.g., “SampleData”, “Selva”, “Niles”), along with features of the tags (manufacturer tag ID, burst, and transmit frequency).</p>
<p>Let’s get a data frame of these, and do some plots to see where there may be issues.</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambigTags</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">ambigID</span>, <span class="va">motusTagID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<p>Using our <code>getpath()</code> function, we’ll create paths and then plot these detections. We’ll add some information to the plot, showing where (in time) the tags are actually ambiguous. We can then inspect the overall plots (or portions of them) to determine if we can contextually unambiguously assign a detection of an ambiguous tag to a single deployment.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.path</span> <span class="op">&lt;-</span> <span class="fu">fun.getpath</span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, 
                                      <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">df.ambigTags</span><span class="op">$</span><span class="va">motusTagID</span>, 
                                      <span class="va">tagProjID</span> <span class="op">==</span> <span class="fl">176</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="co"># create a boolean variable for ambiguous detections:</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Ambiguous <span class="op">=</span> <span class="op">!</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </code></pre></div>
<pre><code>## `summarise()` has grouped output by 'motusTagID', 'runID', 'recvDeployName', 'ambigID', 'tagDepLon', 'tagDepLat', 'recvLat'. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># to put all ambiguous tags from the same project on the same plot together, we</span>
<span class="co"># need to create a new 'ambig tag' variable we call 'newID.</span>

<span class="va">ambigTags.2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">ambigID</span>, <span class="va">motusTagID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>newID <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">ambigID</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/toString.html">toString</a></span><span class="op">(</span><span class="va">motusTagID</span><span class="op">)</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">df.ambigTags</span>, by <span class="op">=</span> <span class="st">"ambigID"</span><span class="op">)</span>

<span class="co"># and merge that with df.alltags.path</span>
<span class="va">df.alltags.path</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">df.alltags.path</span>, <span class="va">ambigTags.2</span>, by <span class="op">=</span> <span class="st">"motusTagID"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">ts.h</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.alltags.path</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts.h</span>, y <span class="op">=</span> <span class="va">recvLat</span>, group <span class="op">=</span> <span class="va">Ambiguous</span>, colour <span class="op">=</span> <span class="va">Ambiguous</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">newID</span>, scales <span class="op">=</span> <span class="st">"free"</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-24-1.png" width="700"></p>
<p>Let’s deal with the easy ones first.</p>
<p><strong>ambigID -337: <code>motusTagID</code>s 10811 and 16011</strong></p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">337</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagDeployStart</span>, <span class="va">tagDeployEnd</span>, <span class="va">tagDepLat</span>, <span class="va">tagDepLon</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID      tagDeployStart        tagDeployEnd tagDepLat tagDepLon n
## 1      10811 2014-10-28 07:00:00 2015-08-03 07:00:00   39.1140  -74.7142 4
## 2      16011 2015-08-02 11:39:59 2015-12-17 11:39:59   51.4839  -80.4500 4</code></pre>
<p>We can see from the plot that ambiguous tag -337 is ambiguous only at the beginning of the deployment.</p>
<p>We can see from the summary of the tag deployment data that there were only 4 detections, at the exact latitude of deployment of tag 16011, and just before the non-ambiguous detections of <code>motusTagID</code> 16011. So the issue here is simply that the tail end of the deployment of tag 10811 slightly overlaps with the deployment of tag 16011. We can confidently claim these detections as belonging to motusTagID 16011, and remove the ambiguous detections assigned to the other tag.</p>
<p>We’ll create another data frame to keep track of these runs.</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># we want the detections associated with the motusTagID that we want to </span>
<span class="co"># ultimately REMOVE from the data frame </span>
<span class="va">df.block.2</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">337</span>,
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">10811</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -134: motusTagIDs 22905 and 23319</strong></p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">134</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagDeployStart</span>, <span class="va">tagDeployEnd</span>, 
           <span class="va">tagDepLat</span>, <span class="va">tagDepLon</span>, <span class="fu"><a href="https://lubridate.tidyverse.org/reference/month.html">month</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID      tagDeployStart        tagDeployEnd tagDepLat tagDepLon
## 1      22905 2016-10-01 16:00:00 2017-06-12 16:00:00  50.19278 -63.74528
## 2      23319 2016-10-15 16:00:00 2017-06-26 16:00:00  50.19278 -63.74528
##   month(ts)     n
## 1        10 22279
## 2        10 22279</code></pre>
<p>Here we have a similar situation, but one that is a bit more complex. Two identical tags were deployed at the same location, shortly after one another. Let’s examine a simple plot.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, 
                     <span class="va">motusTagID</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">22905</span>, <span class="fl">23319</span><span class="op">)</span><span class="op">)</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, group <span class="op">=</span> <span class="va">recvDeployName</span>, colour <span class="op">=</span> <span class="va">recvDeployName</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Time"</span>, y <span class="op">=</span> <span class="st">"Signal strength"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span><span class="va">recvLon</span> <span class="op">~</span> <span class="va">.</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-27-1.png" width="700"></p>
<p>It appears that these are overlapping detections, at two sites in proximity to one another. Additional information from the field researchers may enable us to disentangle them, but it is not clear from the data.</p>
<p>We will therefore remove all detections of this ambiguous tag from the database.</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># we want the detections associated with the motusTagID that we want to </span>
<span class="co"># ultimately REMOVE from the data frame </span>

<span class="va">df.block.3</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">134</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -171: motusTagIDs 22778, 22902 and 22403</strong></p>
<p>The ambiguous detections for this tag, which occur in the Great Lakes region, could also belong to <code>motusTagID</code> 22778 from the RBrownAMWO project or <code>motusTagID</code> 24303 from the Neonics project. Let’s take a closer look at these detections.</p>
<p>First, find the deployment dates and locations for each tag.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID tagProjID               start                 end      lat
## 1      22902       176 2016-10-01 16:00:00 2017-06-12 16:00:00 50.19278
## 2      22778        82 2016-10-21 00:00:00 2018-09-09 00:00:00 45.13535
## 3      24303       146 2017-05-10 22:30:59 2017-06-30 22:30:59 42.60600
##         lon               species
## 1 -63.74528              Red Knot
## 2 -67.29323     American Woodcock
## 3 -80.46900 White-crowned Sparrow</code></pre>
<p>And plot the ambiguous detections.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.171</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, <span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.171</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">port</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>axis.text.x <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>angle <span class="op">=</span> <span class="fl">45</span>, vjust <span class="op">=</span> <span class="fl">1</span>, hjust <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"loess"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span> <span class="op">~</span> <span class="va">recvDeployName</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula 'y ~ x'</code></pre>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-30-1.png" width="700"></p>
<p>We see that there are a large number of ambiguous detections on 10 May 2017 at Old Cut (Long Point, Lake Erie, Ontario), consistent with a bird ‘hanging around’. These are almost certainly detections of motusTagID ‘24303’ which was deployed at Old Cut on 10 May 2017. Subsequent detections on the 18th of May are near Old Cut (Bird Studies Canada HQ, Port Rowan, Ontario), and then a location to the North of Old Cut (Hagersville, Ontario). These detections are consistent with a bird departing on migration. Note in particular the pattern in the latter two panels of increasing then decreasing signal strength which indicates a bird is flying through the beam of an antenna.</p>
<p>These detections belong to another project, so we simply remove all detections of that ambiguous tag from our database.</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># we want the detections associated with the motusTagID that we want to </span>
<span class="co"># ultimately REMOVE from the data frame </span>
<span class="va">df.block.4</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">171</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -114: motusTagIDs 22897 and 24298</strong></p>
<p>Next we look at the ambiguities for ambiguous tag -114.</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID tagProjID               start                 end      lat
## 1      22897       176 2016-10-01 16:00:00 2017-06-12 16:00:00 50.19278
## 2      24298       146 2017-05-10 03:00:00 2017-06-30 03:00:00 42.60690
##         lon               species
## 1 -63.74528              Red Knot
## 2 -80.46900 White-crowned Sparrow</code></pre>
<p>We again subset these and plot them. An initial plot suggested that all of the detections are of a migratory flight, so we construct a somewhat different plot from the one above, that emphasizes this behaviour better.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.114</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>LatLonStationName <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, sep<span class="op">=</span><span class="st">": "</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.114</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, colour <span class="op">=</span> <span class="va">LatLonStationName</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-33-1.png" width="700"></p>
<p>Notice that the detections are consistent with a migratory departure from the Long Point area (Old Cut Field Station, Lake Erie, Ontario) about a week after the ambiguous tag 24298 was deployed at the same location. This again suggests that these ambiguous detections can be removed from our data because they belong to another project.</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.5</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">114</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -106: motusTagIDs 17021 and 17357</strong></p>
<p>These two tags pose an interesting problem. There is only a short period of overlap, between mid August 2015 and mid September. One individual is a Grey-cheeked Thrush, tagged in Colombia, the other a White-rumped Sandpiper, associated with the sample project.</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID tagProjID               start                 end      lat
## 1      17021        57 2015-04-30 05:00:00 2015-09-14 05:00:00 11.12265
## 2      17357       176 2015-08-11 07:20:00 2015-12-26 07:20:00 51.48390
##         lon                species
## 1 -74.08735    Gray-cheeked Thrush
## 2 -80.45000 White-rumped Sandpiper</code></pre>
<p>We plot the ambiguous detections to examine the period of overlap.</p>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.106</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, <span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.106</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-36-1.png" width="700"></p>
<p>Both sets of detections are long run lengths, and look valid (increasing then decreasing signal strength). They are about a day apart, and so it is possible they represent two different birds, or the departure flight of the white-rumped sandpiper from its staging ground. Let’s use the <code><a href="../../reference/siteTrans.html">siteTrans()</a></code> function (in the <code>motus</code> package, see section @ref(siteTrans)) to examine the flight from Netitishi to MDR/Seal (in the Gulf of Maine)</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.106</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">17021</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># just pick one of the two ambiguous IDs</span>
  <span class="fu"><a href="../../reference/siteTrans.html">siteTrans</a></span><span class="op">(</span>latCoord <span class="op">=</span> <span class="st">"recvLat"</span>, lonCoord <span class="op">=</span> <span class="st">"recvLon"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rate</span> <span class="op">&lt;</span> <span class="fl">60</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># remove the simultaneous detections from Seal and MDR</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total.time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/period_to_seconds.html">seconds_to_period</a></span><span class="op">(</span><span class="va">tot_ts</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>start <span class="op">=</span> <span class="va">recvDeployName.x</span>, end <span class="op">=</span> <span class="va">recvDeployName.y</span>, 
         date <span class="op">=</span> <span class="va">ts.x</span>, `rate(m/s)` <span class="op">=</span> <span class="va">rate</span>, 
         <span class="va">dist</span>, total.time <span class="op">=</span> <span class="va">total.time</span>, <span class="va">bearing</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   start       end      date                `rate(m/s)`   dist total.time bearing
##   &lt;chr&gt;       &lt;chr&gt;    &lt;dttm&gt;                    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 Netitishi_… MDR_44,… 2015-09-02 04:18:42        17.1 1.21e6      70879    128.</code></pre>
<p>These detections are &gt;1200 km distant from one another, but the flight speed (17 m/s) is consistent with a white-rumped Sandpiper. Given that the Gray-cheeked Thrush tag was near the end of its expected lifetime, we can reasonably claim these detections for our project, and remove the ambiguous detections associated with <code>motusTagID</code> 17021.</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.block.6</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">106</span>, <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">17021</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><strong>ambigID -56: motusTagIDs 22867 and 23316</strong></p>
<p>These two tags were also both deployed by the same project.</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">tagDeployStart</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">tagProjID</span>, start <span class="op">=</span> <span class="va">tagDeployStart</span>, end <span class="op">=</span> <span class="va">tagDeployEnd</span>, 
         lat <span class="op">=</span> <span class="va">tagDepLat</span>, lon <span class="op">=</span> <span class="va">tagDepLon</span>, species <span class="op">=</span> <span class="va">speciesEN</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">start</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/compute.html">collect</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   motusTagID tagProjID               start                 end      lat
## 1      22867       176 2016-09-06 15:35:00 2017-05-18 15:35:00 51.79861
## 2      23316       176 2016-10-02 16:00:00 2017-06-13 16:00:00 50.19278
##         lon            species
## 1 -80.69139 Pectoral Sandpiper
## 2 -63.74528           Red Knot</code></pre>
<p>Tag 23316 was deployed by the James Bay Shorebird Project (sample project) about three weeks after tag 22867, which was deployed from a location far to the west.</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.ambig.56</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sig <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">sig</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="va">sig</span> <span class="op">*</span> <span class="op">-</span><span class="fl">1</span>, <span class="va">sig</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.ambig.56</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">recvLon</span>, y <span class="op">=</span> <span class="va">ts</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, sep<span class="op">=</span><span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name<span class="op">=</span><span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-40-1.png" width="700"></p>
<p>We can see from the plot that a tag is detected consistently near longitude -65, which is near the deployment location for <code>motusTagID</code> 23316 and after it’s deployment start date, it was also present at -65 during and after detections far to the west. It’s likely all the detections at -65 belong to <code>motusTagID</code> 23316, but it is also clear that anything informative about this ambiguity occurs between about 9-11 October, so let’s zoom in on that part of the data set.</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ts.begin</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/ymd_hms.html">ymd_hms</a></span><span class="op">(</span><span class="st">"2016-10-06 00:00:00"</span><span class="op">)</span>
<span class="va">ts.end</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/ymd_hms.html">ymd_hms</a></span><span class="op">(</span><span class="st">"2016-10-12 23:00:00"</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.ambig.56</span>, 
                     <span class="va">ts</span> <span class="op">&gt;</span> <span class="va">ts.begin</span>, 
                     <span class="va">ts</span> <span class="op">&lt;</span> <span class="va">ts.end</span><span class="op">)</span>,
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">recvLon</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> </code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-41-1.png" width="700"></p>
<p>We can see that the ambiguous tag was detected consistently at Niapiskau and Grand Ile before and after the period when it was also detected to the north and west (at Washkaugou and Piskwamish) and then to the south (NBNJ, SHNJ, and CONY). We can look at this transition by filtering out the portion of the data not near Niapiskau, and again using the siteTrans function from the <code>motus</code> package.</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># other tag is a duplicate</span>
<span class="va">df.56.tmp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.ambig.56</span>, <span class="op">!</span><span class="op">(</span><span class="va">recvLat</span> <span class="op">==</span> <span class="fl">50.2</span><span class="op">)</span>, <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">22867</span><span class="op">)</span> 

<span class="fu"><a href="../../reference/siteTrans.html">siteTrans</a></span><span class="op">(</span><span class="va">df.56.tmp</span>, latCoord <span class="op">=</span> <span class="st">"recvLat"</span>, lonCoord <span class="op">=</span> <span class="st">"recvLon"</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rate</span> <span class="op">&lt;</span> <span class="fl">60</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> <span class="co"># get rid of simultaneous detections</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total.time <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://lubridate.tidyverse.org/reference/period_to_seconds.html">seconds_to_period</a></span><span class="op">(</span><span class="va">tot_ts</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>start <span class="op">=</span> <span class="va">recvDeployName.x</span>, 
         end <span class="op">=</span> <span class="va">recvDeployName.y</span>, 
         date <span class="op">=</span> <span class="va">ts.x</span>, `rate(m/s)` <span class="op">=</span> <span class="va">rate</span>, 
         <span class="va">dist</span>, total.time <span class="op">=</span> <span class="va">total.time</span>, <span class="va">bearing</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   start      end       date                `rate(m/s)`   dist total.time bearing
##   &lt;chr&gt;      &lt;chr&gt;     &lt;dttm&gt;                    &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1 Piskwamis… Washkaug… 2016-10-09 22:49:59        20.3 7.63e4       3767    137.
## 2 Washkaugo… SHNJ_40.… 2016-10-10 00:00:42        24.3 1.27e6      52386    157.</code></pre>
<p>The bird made a 14.5 hour flight between Washkaugou and SHNJ at a rate of 24 m/s, which is plausible. The researchers involved may have other data to support or refute the inference (e.g. an actual sighting of the Red Knot still in Niapiskau after this flight was recorded) but it seems likely that while one tag remained at sites around longitude -65, another tag made the above migratory flights.<br>
We can make another more detailed plot of signal strength to examine these potential migratory flights more closely:</p>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.56.tmp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, <span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, <span class="va">recvLon</span> <span class="op">&lt;</span> <span class="op">-</span><span class="fl">70</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">df.56.tmp</span>, 
       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ts</span>, y <span class="op">=</span> <span class="va">sig</span>, 
           colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">recvLat</span>, <span class="va">recvLon</span>, <span class="va">recvDeployName</span>, sep <span class="op">=</span> <span class="st">": "</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_colour_discrete</a></span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Lat/Lon and\nStation Name"</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="fu"><a href="https://lubridate.tidyverse.org/reference/as_date.html">as_date</a></span><span class="op">(</span><span class="va">ts</span><span class="op">)</span>, scales <span class="op">=</span> <span class="st">"free_x"</span><span class="op">)</span></code></pre></div>
<p><img src="05-data-cleaning_files/figure-html/unnamed-chunk-43-1.png" width="700"></p>
<p>These look like typical fly-by patterns of increasing and then decreasing signal strength.<br>
This, coupled with overall detection patterns and knowledge of the species, leads us to believe that the ambiguous detections can be reasonably divided between the two individuals; one detected consistently around longitude -65 (23316), and the other migrating SW during the same period (22867).</p>
<p>To address this problem, we need to create two filters - one that excludes ambiguous detections of tag 22867, and one that excludes some detections of 23316. In this instance, we can do this most easily by filtering on <code>motusTagID</code> and <code>recvDeployName.</code></p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># tag 23316 was only ever at "Grand-Ile", "Niapiskau", and tag 22867 was never</span>
<span class="co"># detected at those sites. So we exclude all detections not at "Grand-Ile",</span>
<span class="co"># "Niapiskau" for motusTag 23316, and do the opposite for tag 22867.</span>

<span class="va">df.block.7</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, 
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">23316</span>, 
         <span class="op">!</span><span class="op">(</span><span class="va">recvDeployName</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Grand-Ile"</span>, <span class="st">"Niapiskau"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span>

<span class="va">df.block.8</span> <span class="op">&lt;-</span> <span class="va">df.alltags.sub</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ambigID</span> <span class="op">==</span> <span class="op">-</span><span class="fl">56</span>, 
         <span class="va">motusTagID</span> <span class="op">==</span> <span class="fl">22867</span>, 
         <span class="va">recvDeployName</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Grand-Ile"</span>, <span class="st">"Niapiskau"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">motusTagID</span>, <span class="va">runID</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
</div>
<div id="checking-validity-of-run-lengths-of-2-or-3" class="section level2">
<h2 class="hasAnchor">
<a href="#checking-validity-of-run-lengths-of-2-or-3" class="anchor"></a>Checking validity of run lengths of 2 or 3</h2>
<p>At the beginning of this chapter, we dropped all detections with a run length of 2 or 3 or a run length of 4 in noisy conditions, because they are considered to have a high probability of being false positive. Now that we’ve cleaned the data, and are confident in the detections that remain, you might at this point decide to go back and take a closer look at those omitted detections. You could do this, for example, by re-running the various plots described in this chapter (begin with lat/lon by time plots), to see if any of those detections make sense in the context of where the true detections lie. It is up to the user to decide which detections are reasonable in terms of the biology and behaviour of each tagged individual.</p>
</div>
<div id="filtering-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#filtering-the-data" class="anchor"></a>Filtering the data</h2>
<div id="filter-and-save-to-rds" class="section level3">
<h3 class="hasAnchor">
<a href="#filter-and-save-to-rds" class="anchor"></a>Filter and save to RDS</h3>
<p>To filter the data, we can omit rows in the <code>df.block</code> data frames from the original data using a <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code>, which removes rows from <code>x</code> (<code>df.alltags.sub</code>) which are present in <code>y</code> (<code>df.block</code>).</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># combine our df.block data frames into a single dataframe</span>
<span class="va">df.block.all</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span><span class="va">df.block.0</span>, <span class="va">df.block.2</span>, <span class="va">df.block.3</span>,
                          <span class="va">df.block.4</span>, <span class="va">df.block.5</span>, <span class="va">df.block.6</span>, <span class="va">df.block.7</span>, 
                          <span class="va">df.block.8</span><span class="op">)</span>


<span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, <span class="va">df.block.all</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"runID"</span>, <span class="st">"motusTagID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Now save the local data frame as an RDS file, for use in the next chapter. Recall from <a href="03-accessing-data.html#exporting-detections">Exporting detections in Chapter 3</a> that the RDS format preserves the R data structure, including time stamps. The other benefit of saving to RDS is that you have the output from a given workflow saved as a flat file, which you can access again with a simple <code>readRDS</code> statement.</p>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">saveRDS</a></span><span class="op">(</span><span class="va">df.alltags.sub</span>, file <span class="op">=</span> <span class="st">"./data/dfAlltagsSub.rds"</span><span class="op">)</span></code></pre></div>
<p>And to read the data in again:</p>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span><span class="op">(</span><span class="st">"./data/dfAlltagsSub.rds"</span><span class="op">)</span></code></pre></div>
</div>
<div id="saveFilter" class="section level3">
<h3 class="hasAnchor">
<a href="#saveFilter" class="anchor"></a>Save a custom filter in the motus database, and apply it to the data</h3>
<p>As an alternative to saving your data as an RDS file, the Motus R package offers functionalities to save your filters directly within your <code>.motus</code> file. Once they are saved in your database, you can do the type of <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code> as above without having to rely on dataframes or an RDS file to store your data. To learn more about the functions available to work with Motus filters, refer to <a href="%7B#appendixD%7D">Appendix D</a> for more details.</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># combine our df.block data frames into a single dataframe</span>
<span class="va">df.block.all</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind.html">bind_rows</a></span><span class="op">(</span><span class="va">df.block.0</span>, <span class="va">df.block.2</span>, <span class="va">df.block.3</span>, 
                          <span class="va">df.block.4</span>, <span class="va">df.block.5</span>, <span class="va">df.block.6</span>, <span class="va">df.block.7</span>, 
                          <span class="va">df.block.8</span><span class="op">)</span> <span class="op"><a href="../../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>probability <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="co"># create a new filter with name filtAmbigFalsePos and populate it with df.block.all</span>
<span class="va">tbl.filter</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/writeRunsFilter.html">writeRunsFilter</a></span><span class="op">(</span><span class="va">sql.motus</span>, <span class="st">"filtAmbigFalsePos"</span>, 
                              df <span class="op">=</span> <span class="va">df.block.all</span>, delete <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning in createRunsFilter(src, filterName, motusProjID, update = FALSE):
## Warning: filter already exists. Use createRunsFilter function with update=TRUE
## if you want to update the properties (e.g. name) of the existing filter.</code></pre>
<pre><code>## Filter records saved</code></pre>
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># obtain a table object where the filtered records from tbl.filter.1 have been removed</span>
<span class="va">tbl.alltags.sub</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">tbl.alltags</span>, <span class="va">tbl.filter</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"runID"</span>, <span class="st">"motusTagID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><strong>Next:</strong> <a href="06-exploring-data.html">Chapter 6 - Exploring detections data</a></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by John Brzustowski, Denis LePage, Birds Canada.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
