on:
  push:
    branches:
      - master
      - book-overhaul
      
name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: >
            circular
            DT
            geosphere
            kableExtra
            maps
            mapproj
            pander
            patchwork
            pkgdown
            remotes
            tidyverse
          needs: website

      - name: Install dependencies
        run: |
          remotes::install_github("MotusWTS/motusData")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy English Docs
        if: contains(github.ref, "book-overhaul")
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          cp _pkgdown_en.yml _pkgdown.yml
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          rm _pkgdown.yml
      - name: Deploy French Docs
        if: contains(github.ref, "book-overhaul")
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          cp _pkgdown_fr.yml _pkgdown.yml
          cp pkgdown/README_fr.md pkgdown/index.md
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          rm _pkgdown.yml
          rm pkgdown/index.md
      - name: Deploy English DEV Docs
        if: contains(github.ref, "beta")
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          cp _pkgdown_en.yml _pkgdown.yml
          sed -i 's/mode: release/mode: dev/g' _pkgdown.yml
          sed -i 's/motus\//motus\/dev/g' _pkgdown.yml
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          rm _pkgdown.yml
      - name: Deploy French DEV Docs
        if: contains(github.ref, "beta")
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          cp _pkgdown_fr.yml _pkgdown.yml
          cp pkgdown/README_fr.md pkgdown/index.md
          sed -i 's/destination: fr/destination: dev_fr/g' _pkgdown.yml
          sed -i 's/motus\/fr/motus\/dev_fr/g' _pkgdown.yml
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
          rm _pkgdown.yml
          rm pkgdown/index.md
